import { when } from "./dsl";
import type { StoryDef } from "./types";

export const emberCrown: StoryDef = {
  slug: "the-ember-crown",
  title: "The Ember Crown",
  tagline: "The crown has chosen no one for twenty years. Now it is burning in your hands.",
  description:
    "The kingdom of Aurelith has been without a true ruler for twenty years. You are an ordinary royal archivist until an assassination attempt forces you to flee the capital with Kael Ardyn, a disgraced knight accused of treason. During the journey you discover something impossible: the Ember Crown responds to you. You may be the person who decides whether the kingdom survives.",
  genres: ["Fantasy", "Adventure", "Romance", "Political Intrigue"],
  rating: "16+",
  setting: "Aurelith, a kingdom of ash-gold cities, frozen passes and dragon-haunted ruins",
  tone: "Epic, emotional, dangerous, cinematic",
  cover: { from: "#c2410c", to: "#3b0764", emoji: "👑", image: "/covers/the-ember-crown.jpg" },
  stats: [
    { id: "honour", label: "Honour" },
    { id: "magic", label: "Magic" },
    { id: "mercy", label: "Mercy" },
    { id: "mystery", label: "Insight" },
  ],
  characters: [
    {
      id: "kael",
      name: "Kael Ardyn",
      role: "Disgraced knight",
      blurb: "Accused of murdering the prince. Protective, dry-humoured and carrying more guilt than any one person should.",
      color: "#fdba74",
      emoji: "🗡️",
      rel: ["trust", "affection"],
    },
    {
      id: "maren",
      name: "Lady Maren Voss",
      role: "Speaker of the royal council",
      blurb: "Pragmatic, frightened for the realm, and perhaps the only person on the council who can still be reasoned with.",
      color: "#c4b5fd",
      emoji: "⚖️",
      rel: ["trust"],
    },
    {
      id: "shadow",
      name: "The Shadow King",
      role: "The thing on the throne",
      blurb: "An entity that has worn a dead king's face for twenty years.",
      color: "#94a3b8",
      emoji: "🕳️",
      rel: [],
    },
    {
      id: "dragon",
      name: "Vaerhyl",
      role: "Guardian of the second fragment",
      blurb: "An ancient dragon who asks one question and listens to the answer.",
      color: "#fca5a5",
      emoji: "🐉",
      rel: [],
    },
  ],
  flags: {
    trusted_kael: { label: "Trusted Kael" },
    saved_village: { label: "Saved the burning village" },
    used_dark_magic: { label: "Used forbidden magic" },
    hidden_vision: { label: "Hid the Ember's vision from Kael", secret: true },
    shared_vision: { label: "Shared the vision with Kael", secret: true },
    trusted_council: { label: "Gave the fragment to the council" },
    stole_fragment: { label: "Slipped out of the fortress with the fragment", secret: true },
    council_escort: { label: "Accepted the council's escort" },
    spoke_to_maren: { label: "Spoke honestly to Lady Maren" },
    crown_spoke: { label: "Heard the Crown's voice", secret: true },
    ember_control: { label: "Learned to bend the Crown's will" },
    sacrifice_ready: { label: "Told the dragon you would sacrifice yourself" },
    rescued_kael: { label: "Rescued Kael" },
    secret_route: { label: "Used the old catacombs", secret: true },
    maren_ally: { label: "Won Lady Maren's conscience", secret: true },
    bargained: { label: "Bargained with the council" },
    betrayed_kael: { label: "Gave the fragments to the council" },
  },
  items: { village_token: "Villager's token" },
  nodes: [
    {
      key: "S3_N01",
      ch: 1,
      title: "The Assassination",
      start: true,
      text: [
        "The royal archive erupts into chaos. Glass shatters. Guards scream. Ink spills across three centuries of treaties.",
        "A masked attacker steps through the smoke with a curved blade, and a man in battered armour drags you out from behind the shelving.",
        "KAEL: Run.",
      ],
      choices: [
        {
          k: "a",
          t: "Follow Kael.",
          to: "S3_N02",
          fx: { d: { "kael.trust": 1 }, f: ["trusted_kael"] },
        },
        {
          k: "b",
          t: "Stay and protect the archive.",
          to: "S3_N02",
          fx: { d: { honour: 1 } },
          echo: "Kael hesitates only a heartbeat. Then he drags you out anyway.",
        },
        {
          k: "c",
          t: "Fight beside Kael.",
          to: "S3_N02",
          gems: 15,
          fx: { d: { "kael.trust": 2, "kael.affection": 1, honour: 1 } },
        },
      ],
    },
    {
      key: "S3_N02",
      ch: 1,
      title: "The Escape",
      text: [
        "You escape through ancient tunnels beneath the capital, water dripping onto your collar. Kael finally removes his helmet. He is younger than you expected.",
        "YOU: They said you murdered the prince.",
        "KAEL: They say many things about me.",
        "YOU: Did you?",
        "He looks directly at you.",
        "KAEL: No.",
      ],
      choices: [
        { k: "a", t: "Ask what really happened.", to: "S3_N03", fx: { d: { "kael.trust": 1 } } },
        {
          k: "b",
          t: "Accuse him of hiding something.",
          to: "S3_N03",
          fx: { d: { "kael.trust": -1 } },
          echo: "\"Perhaps,\" he says quietly. \"Everyone does.\"",
        },
        { k: "c", t: "Stay silent, and keep walking.", to: "S3_N03", fx: { d: { honour: 1 } } },
      ],
    },
    {
      key: "S3_N03",
      ch: 2,
      title: "The Burning Village",
      text: [
        "Two days from the capital you crest a hill and see a village burning under attack by royal soldiers. The smoke is visible for miles.",
        "Kael wants to continue. The crown's assassins are following you. Every hour matters.",
        "KAEL: We can't save everyone.",
        "Below, somewhere, a child is screaming for her mother.",
      ],
      choices: [
        {
          k: "a",
          t: "Help the villagers.",
          to: "S3_N04A",
          major: true,
          fx: { d: { mercy: 2 }, f: ["saved_village"] },
        },
        {
          k: "b",
          t: "Continue toward the border.",
          to: "S3_N04B",
          major: true,
          fx: { d: { honour: -1 } },
        },
        {
          k: "c",
          t: "Use forbidden magic to stop the soldiers.",
          to: "S3_N04C",
          major: true,
          fx: { d: { magic: 2 }, f: ["used_dark_magic"] },
        },
      ],
    },
    {
      key: "S3_N04A",
      ch: 2,
      title: "Ash and Gratitude",
      text: [
        "You drag people from burning houses until your arms ache. Kael, after one long look at you, draws his sword and does the rest.",
        "When the soldiers are gone, an old woman presses a small carved token into your palm.",
        "OLD WOMAN: A villager's token. Show it in the north and they will open their doors.",
        "Kael watches you across the wreckage of the village square, and something in his face has changed. He looks like a man recalculating.",
      ],
      next: "S3_N04",
      fx: { d: { "kael.affection": 1 }, i: ["village_token"] },
    },
    {
      key: "S3_N04B",
      ch: 2,
      title: "The Quiet Road",
      text: [
        "You turn away from the smoke. Kael walks beside you without a word.",
        "The screaming follows you for a mile, then two, and then it becomes a silence that is somehow heavier.",
        "That night Kael sits with his back to the fire.",
        "KAEL: I've done that before. Walked away. I told myself it was duty.",
        "He doesn't say anything else. He doesn't have to.",
      ],
      next: "S3_N04",
    },
    {
      key: "S3_N04C",
      ch: 2,
      title: "What the Fire Cost",
      text: [
        "The words come to you out of old forbidden texts you were supposed to catalogue, not read. The air screams. The soldiers fall where they stand.",
        "Your hands are black to the wrist. The veins glow faintly, like coals.",
        when({ flags: ["trusted_kael"] }, "Kael catches you as you stagger. He doesn't pull away, but his grip is very careful."),
        "KAEL: Promise me you'll never do that again.",
        "You don't promise. You aren't certain you can.",
      ],
      next: "S3_N04",
    },
    {
      key: "S3_N04",
      ch: 3,
      title: "The Ember",
      text: [
        "The following night you discover a glowing fragment inside an ancient ruin. Kael watches as it rises from its pedestal into your hands.",
        "KAEL: The Ember Crown.",
        "It burns without hurting you. A vision opens behind your eyes: the kingdom falls. Then another: you sit on the throne, and beside you, in the place a consort would stand, is Kael.",
        when({ flags: ["used_dark_magic"] }, "In the vision your eyes are the colour of embers, and your hands are black."),
      ],
      choices: [
        {
          k: "a",
          t: "Tell Kael everything you saw.",
          to: "S3_N05",
          fx: { d: { "kael.trust": 2 } },
        },
        {
          k: "b",
          t: "Hide the vision.",
          to: "S3_N05",
          fx: { d: { mystery: 1 }, f: ["hidden_vision"] },
        },
        {
          k: "c",
          t: "Show Kael the complete vision.",
          to: "S3_N05",
          gems: 20,
          fx: { d: { "kael.trust": 2, "kael.affection": 2 }, f: ["shared_vision"] },
        },
      ],
    },
    {
      key: "S3_N05",
      ch: 4,
      title: "The Council",
      text: [
        "You arrive at an allied fortress. The royal council demands the Ember fragment, claiming you are too dangerous to possess it.",
        "Lady Maren Voss sits at the head of the table, hands folded. She is the only one who doesn't shout.",
        when({ flags: ["used_dark_magic"] }, "They have heard about the village. The word \"witch\" is used twice."),
        "Kael steps between you and them.",
        "KAEL: You wanted a traitor.",
        "He draws his sword.",
        "KAEL: You found one.",
      ],
      choices: [
        {
          k: "a",
          t: "Trust Kael.",
          to: "S3_N05B",
          major: true,
          fx: { d: { "kael.trust": 2 }, f: ["trusted_kael"] },
        },
        {
          k: "b",
          t: "Give the fragment to the council.",
          to: "S3_N05B",
          major: true,
          fx: { d: { "maren.trust": 2 }, f: ["trusted_council"] },
        },
        {
          k: "c",
          t: "Refuse everyone.",
          to: "S3_N05B",
          major: true,
          fx: { d: { honour: 1 } },
        },
      ],
    },
    {
      key: "S3_N05B",
      ch: 4,
      title: "Midnight in the Fortress",
      text: [
        "Late that night, Lady Maren finds you alone on the battlements.",
        "MAREN: I've buried three kings and one prince. I am very tired of burying people.",
        when({ flags: ["trusted_council"] }, "Behind her a guard carries the fragment in a lead-lined box. \"It's not a prison,\" she says, \"but it isn't quite a gift either.\""),
        when({ notFlags: ["trusted_council"] }, "Her eyes drift to the fragment in your hands. She doesn't reach for it. \"You're very brave, or very foolish. They often look alike.\""),
        "MAREN: Kael is not the man they say he is. I'm not certain you are either. I'd like to know.",
      ],
      choices: [
        {
          k: "a",
          t: "Accept Lady Maren's escort north.",
          to: "S3_N06",
          fx: { d: { "maren.trust": 2 }, f: ["council_escort"] },
        },
        {
          k: "b",
          t: "Slip away before dawn with Kael.",
          to: "S3_N06",
          req: { flags: ["trusted_kael"] },
          lock: "You'd need Kael's trust to leave like this.",
          fx: { d: { "kael.trust": 1, "kael.affection": 1 }, f: ["stole_fragment"] },
          echo: "He laughs silently, breath clouding. It is the first time you've seen him do it.",
        },
        {
          k: "c",
          t: "Tell Lady Maren honestly what the Crown showed you.",
          to: "S3_N06",
          fx: { d: { "maren.trust": 1, honour: 1 }, f: ["spoke_to_maren"] },
        },
      ],
    },
    {
      key: "S3_N06",
      ch: 5,
      title: "The Journey North",
      text: [
        "The second Ember fragment lies beyond the frozen mountains.",
        "On the third day of the climb Kael admits he was ordered to assassinate the former prince.",
        "YOU: Why?",
        "KAEL: Because the prince was innocent.",
        "He pauses.",
        "KAEL: And because someone told me the kingdom could still be saved.",
      ],
      choices: [
        {
          k: "a",
          t: "Ask whether he trusts you.",
          to: "S3_N06B",
          fx: { d: { "kael.affection": 1, "kael.trust": 1 } },
        },
        {
          k: "b",
          t: "Ask who gave him the order.",
          to: "S3_N06B",
          fx: { d: { mystery: 2 } },
        },
        {
          k: "c",
          t: "Tell him you trust him.",
          to: "S3_N06B",
          fx: { d: { "kael.trust": 2, "kael.affection": 1 } },
        },
      ],
    },
    {
      key: "S3_N06B",
      ch: 5,
      title: "The Frozen Pass",
      text: [
        "A blizzard swallows the mountain. You shelter in a crevice with barely room to sit.",
        when({ flags: ["saved_village"] }, "You turn the villager's token over in your fingers. Somewhere in the snow, you think, there are people who would burn their last log for you."),
        when({ flags: ["council_escort"] }, "Lady Maren's guards are huddled in the dark further down the pass. They do not speak."),
        "The cold is the worst kind: patient.",
      ],
      choices: [
        {
          k: "a",
          t: "Share your cloak and body heat with Kael.",
          to: "S3_N07",
          fx: { d: { "kael.affection": 1 } },
          echo: "Neither of you talks about it the next morning. Both of you think about it.",
        },
        {
          k: "b",
          t: "Push on through the storm.",
          to: "S3_N07",
          fx: { d: { honour: 1 } },
        },
        {
          k: "c",
          t: "Light a fire with your magic.",
          to: "S3_N07",
          fx: { d: { magic: 1 } },
        },
      ],
    },
    {
      key: "S3_N07",
      ch: 6,
      title: "The Shadow King",
      text: [
        "In the ruins at the top of the pass you find the truth carved in stone, and the Crown whispers the rest.",
        "The king has been dead for years. The figure sitting on the throne is an illusion maintained by a magical entity called the Shadow King.",
        "The Ember Crown was never meant to protect the monarch. It was meant to destroy the Shadow King.",
        "But using its full power will destroy the royal bloodline, including Kael.",
        when({ flags: ["hidden_vision"] }, "You realise what you didn't tell Kael, and your stomach turns."),
      ],
      choices: [
        {
          k: "a",
          t: "Find another way.",
          to: "S3_N08",
          fx: { d: { magic: 1 } },
        },
        {
          k: "b",
          t: "Destroy the Shadow King immediately.",
          to: "S3_N08",
          fx: { d: { honour: 2 } },
        },
        {
          k: "c",
          t: "Use dark magic to control the Crown.",
          to: "S3_N08",
          req: { gte: { magic: 3 } },
          lock: "You'd need much stronger command of magic.",
          fx: { d: { magic: 2 }, f: ["ember_control"] },
        },
        {
          k: "d",
          t: "Ask the Crown itself what it wants.",
          to: "S3_N08",
          gems: 15,
          fx: { d: { mystery: 2, magic: 1 }, f: ["crown_spoke"] },
        },
      ],
    },
    {
      key: "S3_N08",
      ch: 7,
      title: "The Second Fragment",
      text: [
        "The second fragment is guarded by an ancient dragon, curled around a mountain of black glass. One huge gold eye opens.",
        "VAERHYL: What is worth sacrificing for a kingdom?",
        "The mountain is silent, waiting.",
        when({ flags: ["crown_spoke"] }, "The Crown pulses once in your hand, like a heartbeat, as if the answer matters to it too."),
      ],
      choices: [
        { k: "a", t: "Power.", to: "S3_N09", fx: { d: { honour: -1 } } },
        { k: "b", t: "Love.", to: "S3_N09", fx: { d: { "kael.affection": 1 } } },
        {
          k: "c",
          t: "Myself.",
          to: "S3_N09",
          fx: { d: { mercy: 2 }, f: ["sacrifice_ready"] },
        },
      ],
    },
    {
      key: "S3_N09",
      ch: 8,
      title: "The Betrayal",
      text: [
        "You return to the fortress with both fragments. The gates are open. That is the first thing that feels wrong.",
        "The council has captured Kael. They claim he betrayed you.",
        "MAREN: Give me the fragments and he goes free. I'm sorry. I truly am.",
        when({ gte: { "maren.trust": 3 } }, "Her voice cracks on the last word. Whatever she's ordered to do, she doesn't want to."),
      ],
      choices: [
        {
          k: "a",
          t: "Rescue Kael.",
          to: "S3_N10",
          major: true,
          req: { gte: { "kael.trust": 4 } },
          lock: "Kael doesn't trust you enough to follow you into this.",
          fx: { d: { "kael.affection": 2 }, f: ["rescued_kael"] },
        },
        {
          k: "b",
          t: "Appeal to Lady Maren's conscience.",
          to: "S3_N10",
          major: true,
          req: { gte: { "maren.trust": 3 } },
          lock: "Lady Maren doesn't trust you enough to listen.",
          fx: { d: { "kael.affection": 1 }, f: ["rescued_kael", "maren_ally"] },
        },
        {
          k: "c",
          t: "Secretly rescue Kael through the old catacombs.",
          to: "S3_N10",
          gems: 25,
          major: true,
          fx: { d: { "kael.affection": 3, "kael.trust": 2 }, f: ["rescued_kael", "secret_route"] },
        },
        {
          k: "d",
          t: "Bargain: one fragment for Kael's life.",
          to: "S3_N10",
          major: true,
          fx: { d: { honour: -1, "kael.trust": -1 }, f: ["bargained"] },
        },
        {
          k: "e",
          t: "Give the council the fragments.",
          to: "S3_N10",
          major: true,
          fx: { d: { "kael.trust": -5 }, f: ["betrayed_kael"] },
          echo: "Kael doesn't look at you as they lead him away. That is worse than anything he could have said.",
        },
      ],
    },
    {
      key: "S3_N10",
      ch: 9,
      title: "The Ember Crown",
      text: [
        "The fragments merge. The Ember Crown appears above you, spinning slowly, and three possible futures unfold in its light.",
        "In the first, the kingdom survives and Kael rules beside you.",
        "In the second, the kingdom survives and Kael dies.",
        "In the third, the kingdom burns, and you become the most powerful person alive.",
        when(
          { flags: ["rescued_kael"] },
          "Kael stands at your shoulder, bruised and alive.",
          "KAEL: Whatever happens next...",
          "He reaches for your hand.",
          "KAEL: ...choose it because it is yours.",
        ),
        when({ flags: ["bargained"], notFlags: ["rescued_kael"] }, "Kael leans against the wall, pale and wounded. He watches you with guarded, waiting eyes."),
        when({ flags: ["betrayed_kael"] }, "Kael is somewhere in the dungeons below. You can feel the silence where his voice should be."),
      ],
      next: "S3_N11",
    },
    {
      key: "S3_N11",
      ch: 10,
      title: "The Final Battle",
      text: [
        "The Shadow King attacks, pouring out of the throne like smoke made solid. The walls of the fortress scream.",
        "The Crown demands a sacrifice. It has always demanded one.",
        "You have one moment to decide what kind of ruler you will be.",
      ],
      choices: [
        {
          k: "a",
          t: "Use the Crown's full power.",
          to: "S3_END_01",
          major: true,
        },
        {
          k: "b",
          t: "Sacrifice yourself.",
          to: "S3_END_02",
          major: true,
          req: { gte: { mercy: 4 } },
          lock: "You'd need far greater mercy in your heart.",
        },
        {
          k: "c",
          t: "Control the Crown with dark magic.",
          to: "S3_END_03",
          major: true,
          req: { flags: ["ember_control"] },
          lock: "You haven't learned to bend the Crown's will.",
        },
        {
          k: "d",
          t: "Destroy the Crown.",
          to: "S3_END_04",
          major: true,
          req: { gte: { honour: 4 } },
          lock: "You'd need stronger honour to give up such power.",
        },
        {
          k: "e",
          t: "Lay the Crown at Kael's feet, and share it.",
          to: "S3_END_05",
          major: true,
          req: { flags: ["rescued_kael"], gte: { "kael.affection": 6 } },
          lock: "Kael would need to be at your side, and love you more deeply.",
        },
      ],
    },
    {
      key: "S3_END_01",
      ch: 11,
      title: "The Ember Throne",
      ending: { n: 1, title: "The Ember Throne", type: "hopeful" },
      text: [
        "The Shadow King is destroyed. The kingdom survives. The Ember Crown chooses you.",
        when(
          { flags: ["rescued_kael"] },
          "Kael kneels before you. You pull him back to his feet.",
          "YOU: Don't kneel.",
          "KAEL: Your Majesty?",
          "YOU: Not to me.",
        ),
        when({ gte: { "kael.affection": 6, "kael.trust": 5 } }, "Kael becomes your partner and your commander, and the court learns very quickly never to come between the two of you."),
        when({ flags: ["betrayed_kael"] }, "You rule Aurelith, and you rule it alone. Kael is exiled to the north. You never ask the council where."),
      ],
    },
    {
      key: "S3_END_02",
      ch: 11,
      title: "The Sacrifice",
      ending: { n: 2, title: "The Sacrifice", type: "bittersweet" },
      text: [
        "You sacrifice yourself. The kingdom survives. The Crown shatters, and the Shadow King goes with it.",
        when(
          { flags: ["rescued_kael"] },
          "Years later, Kael leaves flowers beside the ruined throne.",
          "KAEL: You saved everyone.",
          "He looks at the empty throne.",
          "KAEL: I just wish you had saved yourself too.",
        ),
        when({ notFlags: ["rescued_kael"] }, "Kael is alive, because you chose that, too. He doesn't know you did. He simply keeps a small flame burning every night by the throne."),
      ],
    },
    {
      key: "S3_END_03",
      ch: 11,
      title: "The Shadow Crown",
      ending: { n: 3, title: "The Shadow Crown", type: "dark" },
      text: [
        "You bend the Ember Crown to your will. The Shadow King is defeated.",
        "But its power changes you. The kingdom kneels, and each year the kneeling feels more natural.",
        when({ gte: { "kael.affection": 7 } }, "Kael survives and refuses to leave your side, even when you ask him to, even when you're afraid of what you might do to him."),
        when({ lte: { "kael.affection": 6 } }, "Kael survives, and he fears what you have become. In the sequel, he is your greatest opponent."),
      ],
    },
    {
      key: "S3_END_04",
      ch: 11,
      title: "The Crownless Kingdom",
      ending: { n: 4, title: "The Crownless Kingdom", type: "hopeful" },
      text: [
        "You destroy the Crown. Magic disappears from the royal bloodline, and the kingdom must rebuild itself without supernatural power.",
        when(
          { flags: ["rescued_kael"] },
          "Kael stands beside you. There is no throne. No prophecy. No destiny. Only a choice.",
          "KAEL: So what do we do now?",
          "YOU: Something nobody predicted.",
        ),
        when({ notFlags: ["rescued_kael"] }, "There is no throne, no prophecy, no destiny. Only the wide, terrifying open road of a kingdom that has to choose for itself."),
      ],
    },
    {
      key: "S3_END_05",
      ch: 11,
      title: "The Shared Flame",
      ending: { n: 5, title: "The Shared Flame", type: "romance" },
      text: [
        "You do not put the Crown on your own head. You lift it, with both hands, and set it into Kael's.",
        "It flares. The Shadow King screams, and the flame divides between you like a breath shared between two mouths.",
        "For the first time in twenty years, Aurelith has not one ruler but two. The court is scandalised. The villagers are delighted.",
        when({ flags: ["saved_village"] }, "In the north, an old woman lights a candle by an open door, in case her two monarchs ever pass that way."),
        "KAEL: Together, then.",
        "YOU: Together.",
      ],
    },
  ],
};
