import { when } from "./dsl";
import type { StoryDef } from "./types";

export const hollowmereLegacy: StoryDef = {
  slug: "hollow-at-hollowmere",
  title: "The Hollow at Hollowmere",
  tagline: "You were hired to catalogue a library. The house was hiring for something else.",
  description:
    "A crumbling manor on the Yorkshire moors. A reclusive heir who plays the piano at midnight. A housekeeper with too many rules. And a woman's voice singing behind the boarded-up east wing. You've been hired to catalogue the late collector's library, but Hollowmere has been waiting a very long time for someone exactly like you.",
  genres: ["Horror", "Mystery", "Romance", "Gothic"],
  rating: "16+",
  setting: "Hollowmere Manor, a storm-battered house on the Yorkshire moors",
  tone: "Gothic, atmospheric, tender, unsettling",
  cover: { from: "#14532d", to: "#020617", emoji: "🕯️", image: "/covers/the-hollow-at-hollowmere.jpg" },
  stats: [
    { id: "nerve", label: "Nerve" },
    { id: "insight", label: "Insight" },
  ],
  characters: [
    {
      id: "julian",
      name: "Julian Ashcombe",
      role: "Heir to Hollowmere",
      blurb: "Soft-spoken, sleepless and scarred across one hand. He plays the piano as if he were apologising to someone.",
      color: "#86efac",
      emoji: "🎹",
      rel: ["trust", "affection"],
    },
    {
      id: "wren",
      name: "Mrs. Wren",
      role: "The housekeeper",
      blurb: "Has served the Ashcombes for forty years. Keeps the house immaculate, the rules strict and the east wing locked.",
      color: "#fde68a",
      emoji: "🗝️",
      rel: ["trust"],
    },
    {
      id: "adelaide",
      name: "Adelaide Ashcombe",
      role: "The voice in the east wing",
      blurb: "Julian's younger sister. She has been singing the same lullaby for nine years.",
      color: "#c4b5fd",
      emoji: "🕊️",
      rel: [],
    },
    {
      id: "hollow",
      name: "The Hollow",
      role: "What lives in the walls",
      blurb: "It doesn't have a face. It has appetite, and patience, and a very good memory.",
      color: "#64748b",
      emoji: "🌑",
      rel: [],
    },
  ],
  flags: {
    saw_lady: { label: "Saw a figure in the window", secret: true },
    found_ledger: { label: "Found the collector's ledger" },
    silver_key: { label: "Found a small silver key" },
    heard_singing: { label: "Followed the singing" },
    saw_ritual: { label: "Watched Mrs. Wren's evening rites", secret: true },
    saw_portrait: { label: "Uncovered Adelaide's portrait" },
    asked_about_fire: { label: "Asked Julian about the fire" },
    answered_house: { label: "Answered when the house called your name", secret: true },
    stayed_silent: { label: "Stayed silent when it called" },
    spoke_her_name: { label: "Answered with Adelaide's name", secret: true },
    servants_route: { label: "Used the servants' passage", secret: true },
    comforted_adelaide: { label: "Comforted Adelaide" },
    fled_nursery: { label: "Fled the nursery" },
    told_julian: { label: "Told Julian the truth" },
    confronted_wren: { label: "Confronted Mrs. Wren" },
    kept_secret: { label: "Kept the truth to yourself" },
    wren_wavers: { label: "Made Mrs. Wren hesitate", secret: true },
    broke_circle: { label: "Broke the ritual circle", secret: true },
    adelaide_heard: { label: "Made the house listen to Adelaide" },
    sang_song: { label: "Sang Adelaide's lullaby", secret: true },
  },
  items: { silver_key: "Silver key" },
  nodes: [
    {
      key: "S4_N01",
      ch: 1,
      title: "The Drive to Hollowmere",
      start: true,
      text: [
        "The taxi leaves you at the gates and will not go a yard further. The driver doesn't explain. He simply reverses into the rain.",
        "Hollowmere Manor rises out of the fog like a tooth: grey stone, black windows, an east wing with every shutter nailed closed.",
        "A man waits on the steps with a lantern. He is tall and tired-looking, with a scar crossing the back of his left hand.",
        "JULIAN: You must be the archivist. I'm Julian. I'm sorry about the weather. And the house.",
        "Behind him a woman in a grey dress stands as still as a doorframe.",
        "MRS. WREN: Dinner is at seven. We lock the doors at nine. You will not need to go into the east wing.",
      ],
      choices: [
        {
          k: "a",
          t: "Thank Julian warmly for the welcome.",
          to: "S4_N02",
          fx: { d: { "julian.trust": 1, "julian.affection": 1 } },
        },
        {
          k: "b",
          t: "Ask why the east wing's windows are nailed shut.",
          to: "S4_N02",
          fx: { d: { insight: 1, "julian.trust": -1 } },
          echo: "Mrs. Wren's stare could curdle milk. Julian looks at his shoes.",
        },
        {
          k: "c",
          t: "Notice the pale figure in the upstairs window, and lift a hand to her.",
          to: "S4_N02",
          gems: 10,
          fx: { d: { insight: 1, nerve: 1 }, f: ["saw_lady"] },
        },
      ],
    },
    {
      key: "S4_N02",
      ch: 2,
      title: "The Collector's Library",
      text: [
        "The library is magnificent and in ruins: twelve thousand volumes, every one mildewed, every one beautifully bound. Dust hangs in the lamplight like slow smoke.",
        when({ flags: ["saw_lady"] }, "You find yourself glancing up at the ceiling, toward the room where you saw her."),
        "Sir Reginald Ashcombe, the late collector, left ledgers, catalogues and a half-burnt inventory that stops mid-sentence.",
        "As you lift a fallen book, a small object slides from between its pages and rings on the floorboards.",
      ],
      choices: [
        {
          k: "a",
          t: "Read the collector's ledger closely.",
          to: "S4_N03",
          fx: { d: { insight: 1 }, f: ["found_ledger"] },
        },
        {
          k: "b",
          t: "Keep cataloguing. Be a professional.",
          to: "S4_N03",
          fx: { d: { "julian.trust": 1 } },
          echo: "Julian lingers at the door that afternoon. He looks oddly touched by the tidy stacks.",
        },
        {
          k: "c",
          t: "Pick up the small silver key.",
          to: "S4_N03",
          fx: { f: ["silver_key"], i: ["silver_key"] },
        },
      ],
    },
    {
      key: "S4_N03",
      ch: 3,
      title: "The Singing",
      text: [
        "At ten past two, something wakes you.",
        "A woman's voice, thin and sweet, is singing a lullaby. It drifts along the corridor from the east wing, through the wall, and into the room.",
        when({ flags: ["saw_lady"] }, "You recognise the voice. It is the figure from the window."),
        "Somewhere below, the piano answers it, one careful note at a time.",
      ],
      choices: [
        {
          k: "a",
          t: "Follow the singing to the east wing door.",
          to: "S4_N04",
          fx: { d: { nerve: 1 }, f: ["heard_singing"] },
        },
        {
          k: "b",
          t: "Go downstairs to the piano.",
          to: "S4_N04",
          fx: { d: { "julian.trust": 1, "julian.affection": 1 } },
          echo: "He doesn't stop playing when you come in. He just shifts along the bench.",
        },
        {
          k: "c",
          t: "Pull the covers over your head and wait for morning.",
          to: "S4_N04",
          fx: { d: { nerve: -1 } },
        },
      ],
    },
    {
      key: "S4_N04",
      ch: 3,
      title: "Mrs. Wren's Rules",
      text: [
        "In the morning Mrs. Wren serves you tea in the kitchen. She does not sit. Her eyes never leave the window.",
        "MRS. WREN: There are three rules, miss. You do not go into the east wing. You do not go into the cellar. And if you hear your name called in the night, you do not answer.",
        "She says it like a woman reading a recipe she has used for decades.",
        when({ flags: ["heard_singing"] }, "She glances at the mud on your slippers and says nothing, which is somehow worse."),
      ],
      choices: [
        {
          k: "a",
          t: "Promise to follow the rules.",
          to: "S4_N05",
          fx: { d: { "wren.trust": 1 } },
        },
        {
          k: "b",
          t: "Press her on what happens if you break them.",
          to: "S4_N05",
          fx: { d: { insight: 1, "wren.trust": -1 } },
        },
        {
          k: "c",
          t: "Offer to help her with the evening rites.",
          to: "S4_N05",
          gems: 15,
          fx: { d: { insight: 2, "wren.trust": 1 }, f: ["saw_ritual"] },
        },
      ],
    },
    {
      key: "S4_N05",
      ch: 4,
      title: "The Portrait Gallery",
      text: [
        "The gallery upstairs is lined with Ashcombes: stern men, pale wives, a dog with a melancholy face. One frame at the far end is draped with black velvet.",
        when({ flags: ["saw_ritual"] }, "You remember what Mrs. Wren laid out on the kitchen table last night, and the shape the salt made, and you take a careful half-step back."),
        "Julian's footsteps approach along the corridor, slow and measured.",
      ],
      choices: [
        {
          k: "a",
          t: "Lift the velvet and look.",
          to: "S4_N06",
          fx: { d: { nerve: 1 }, f: ["saw_portrait"] },
        },
        {
          k: "b",
          t: "Ask Julian who is under the cloth.",
          to: "S4_N06",
          req: { gte: { "julian.trust": 1 } },
          lock: "Julian doesn't trust you enough to be asked yet.",
          fx: { d: { "julian.affection": 1 } },
        },
        {
          k: "c",
          t: "Leave it alone and move on.",
          to: "S4_N06",
        },
      ],
    },
    {
      key: "S4_N06",
      ch: 5,
      title: "Julian's Piano",
      text: [
        "Julian plays in the drawing room with the lights out, because the moon on the keys is enough. He has a way of playing as though each note might be the last thing he is allowed to say.",
        when({ flags: ["saw_portrait"] }, "You have seen the girl in the portrait now: dark curls, a laugh caught mid-breath. The song he is playing is the one from your walls."),
        "JULIAN: I used to play it for her. She'd fall asleep on the rug.",
        "He doesn't say who. He doesn't need to.",
      ],
      choices: [
        {
          k: "a",
          t: "Sit beside him on the piano bench.",
          to: "S4_N07",
          fx: { d: { "julian.affection": 2 } },
          echo: "His hand hesitates on the keys. Then he plays a little softer, for you.",
        },
        {
          k: "b",
          t: "Ask him, gently, about the fire.",
          to: "S4_N07",
          fx: { d: { "julian.trust": 1, insight: 1 }, f: ["asked_about_fire"] },
        },
        {
          k: "c",
          t: "Leave him in peace and listen from the doorway.",
          to: "S4_N07",
          fx: { d: { "julian.trust": 1 } },
        },
      ],
    },
    {
      key: "S4_N07",
      ch: 6,
      title: "The Name Called",
      text: [
        "Three nights later, at the bottom of a dream, somebody says your name.",
        "It is not a whisper. It is a voice exactly like your own mother's, from the landing outside your door, patient, loving, a little disappointed.",
        "It says it again. And again.",
        when({ flags: ["asked_about_fire"] }, "You think about Julian's scar, and the word he did not say."),
        "Mrs. Wren's first rule turns over and over in your head.",
      ],
      choices: [
        {
          k: "a",
          t: "Answer it.",
          to: "S4_N08",
          major: true,
          fx: { d: { nerve: 1, insight: 1 }, f: ["answered_house"] },
          echo: "Something on the landing is pleased. You feel it like warmth through a keyhole.",
        },
        {
          k: "b",
          t: "Stay silent until dawn.",
          to: "S4_N08",
          major: true,
          fx: { d: { nerve: 2 }, f: ["stayed_silent"] },
        },
        {
          k: "c",
          t: "Answer with Adelaide's name instead.",
          to: "S4_N08",
          gems: 15,
          major: true,
          fx: { d: { insight: 1, nerve: 1 }, f: ["spoke_her_name"] },
        },
      ],
    },
    {
      key: "S4_N08",
      ch: 7,
      title: "The East Wing Door",
      text: [
        "The door to the east wing is sealed with iron hinges, three locks and a cross of rowan wood nailed at head height.",
        when({ flags: ["answered_house"] }, "The locks seem to loosen a little as you approach, like a mouth half-open."),
        when({ flags: ["spoke_her_name"] }, "The singing on the other side stops dead when you say her name aloud. Then, very slowly, it begins again, closer."),
        "Whatever is in there has been waiting for someone to try the handle.",
      ],
      choices: [
        {
          k: "a",
          t: "Try the small silver key.",
          to: "S4_N09",
          req: { items: ["silver_key"] },
          lock: "You don't have a key that fits.",
          fx: { d: { insight: 1 } },
        },
        {
          k: "b",
          t: "Ask Julian to open it with you.",
          to: "S4_N09",
          req: { gte: { "julian.trust": 3 } },
          lock: "Julian would never hold the key for someone he doesn't trust.",
          fx: { d: { "julian.affection": 1 } },
        },
        {
          k: "c",
          t: "Break the rowan cross and force the lock.",
          to: "S4_N09",
          req: { gte: { nerve: 2 } },
          lock: "You don't have the nerve to touch that cross.",
          fx: { d: { nerve: 1 } },
        },
        {
          k: "d",
          t: "Find another way: the servants' passage.",
          to: "S4_N09",
          fx: { d: { nerve: 1, "wren.trust": -1 }, f: ["servants_route"] },
        },
      ],
    },
    {
      key: "S4_N09",
      ch: 8,
      title: "The Nursery",
      text: [
        "The east wing is preserved exactly as it was the night of the fire: scorched wallpaper, a cracked dollhouse, a small bed where the sheets still hold the shape of a sleeper.",
        "A girl stands in the centre of the room with her back to you. She is singing.",
        "When she turns, her face is lovely and cracked like old porcelain, and her eyes are the eyes of someone who has been asking for help for nine years.",
        "ADELAIDE: You came. Nobody comes. Julian comes, but he cannot hear me any more.",
      ],
      choices: [
        {
          k: "a",
          t: "Speak to her gently. Tell her she isn't alone.",
          to: "S4_N10",
          major: true,
          fx: { d: { nerve: 1 }, f: ["comforted_adelaide"] },
        },
        {
          k: "b",
          t: "Demand to know what the house wants.",
          to: "S4_N10",
          fx: { d: { insight: 1 } },
        },
        {
          k: "c",
          t: "Flee back down the corridor.",
          to: "S4_N10",
          fx: { d: { nerve: -1 }, f: ["fled_nursery"] },
        },
      ],
    },
    {
      key: "S4_N10",
      ch: 9,
      title: "The Truth in Ashes",
      text: [
        when({ flags: ["fled_nursery"] }, "You run, but the truth chases you. It plays itself out on the wallpaper behind your eyes, too clear to outrun."),
        "Adelaide shows you, in fragments. The fire was not an accident. Nine years ago the Hollow, the hunger that lives in the house's foundations, came for Julian.",
        "Mrs. Wren, who has loved him since he was a child, made a bargain. The house could keep Adelaide's voice and her spirit, and in return Julian would be spared. Each year on the anniversary it needs a new offering to keep the bargain.",
        "You look at the letter of engagement in your pocket, and its very generous salary, and the date on it.",
        "ADELAIDE: She brought you here to be the next one. She did not want to. She is so tired.",
      ],
      choices: [
        {
          k: "a",
          t: "Tell Julian everything.",
          to: "S4_N11",
          major: true,
          fx: { d: { "julian.trust": 2 }, f: ["told_julian"] },
        },
        {
          k: "b",
          t: "Confront Mrs. Wren first.",
          to: "S4_N11",
          major: true,
          fx: { d: { insight: 1, nerve: 1, "wren.trust": -1 }, f: ["confronted_wren"] },
        },
        {
          k: "c",
          t: "Say nothing until you can see the whole shape of it.",
          to: "S4_N11",
          fx: { d: { insight: 1 }, f: ["kept_secret"] },
        },
      ],
    },
    {
      key: "S4_N11",
      ch: 10,
      title: "The Reckoning at Supper",
      text: [
        "Supper is laid for three. The silver is polished. The candles burn very straight.",
        "Mrs. Wren stands at the head of the table. Julian sits at the foot, understanding nothing. Between them a circle of salt has been drawn into the carpet, small and neat, and the third place setting sits precisely in its centre.",
        when({ flags: ["told_julian"] }, "Julian is already on his feet beside you, his scarred hand around yours."),
        when({ flags: ["confronted_wren"] }, "Mrs. Wren's hands are trembling on the tablecloth. She knows you know."),
        "The candles lean toward you as though the house were breathing in.",
      ],
      choices: [
        {
          k: "a",
          t: "Stand with Julian and tell him in front of her.",
          to: "S4_N12",
          req: { flags: ["told_julian"] },
          lock: "You haven't told Julian the truth yet.",
          fx: { d: { "julian.affection": 1, nerve: 1 } },
        },
        {
          k: "b",
          t: "Appeal to Mrs. Wren. She is not a villain.",
          to: "S4_N12",
          req: { gte: { "wren.trust": 2 } },
          lock: "Mrs. Wren doesn't trust you enough to listen.",
          fx: { d: { insight: 1 }, f: ["wren_wavers"] },
        },
        {
          k: "c",
          t: "Scatter the salt circle before anyone speaks.",
          to: "S4_N12",
          req: { items: ["silver_key"] },
          lock: "You haven't found anything that could break the circle.",
          fx: { d: { nerve: 1 }, f: ["broke_circle"] },
        },
        {
          k: "d",
          t: "Demand that everyone in this house hear Adelaide.",
          to: "S4_N12",
          fx: { d: { nerve: 1 }, f: ["adelaide_heard"] },
        },
      ],
    },
    {
      key: "S4_N12",
      ch: 11,
      title: "The Hollow Wakes",
      text: [
        "The house does not scream. It exhales.",
        "Every door in Hollowmere opens at once. The portraits turn their faces to the wall. The lullaby rises from every room, then breaks into a chord of a hundred voices that are all, somehow, your own.",
        when({ flags: ["wren_wavers"] }, "Mrs. Wren has stopped guarding the circle. She stands with her hands over her mouth, weeping."),
        "Something in the walls is reaching for the third place at the table.",
      ],
      choices: [
        {
          k: "a",
          t: "Stand your ground and sing Adelaide's lullaby.",
          to: "S4_N13",
          req: { flags: ["heard_singing"] },
          lock: "You've never heard the song properly.",
          fx: { d: { insight: 1, nerve: 1 }, f: ["sang_song"] },
        },
        {
          k: "b",
          t: "Seize Julian's hand and run for the stairs.",
          to: "S4_N13",
          req: { gte: { "julian.affection": 3 } },
          lock: "Julian doesn't feel close enough to you to follow.",
          fx: { d: { "julian.affection": 1 } },
        },
        {
          k: "c",
          t: "Brace yourself and wait it out.",
          to: "S4_N13",
          fx: { d: { nerve: 1 } },
        },
      ],
    },
    {
      key: "S4_N13",
      ch: 12,
      title: "The Last Door",
      text: [
        "It is nearly dawn. The house has gone very still, as if weighing you.",
        "You have the front gates at your back and the nursery door in front of you. You have the library's whole catalogue of ghosts, and one pale girl holding out her hand.",
        "Whatever you choose now, Hollowmere will remember it.",
      ],
      choices: [
        {
          k: "a",
          t: "Break the bargain and free Adelaide.",
          to: "S4_END_01",
          major: true,
          req: { anyFlags: ["comforted_adelaide", "spoke_her_name", "sang_song"], gte: { insight: 3 } },
          lock: "You don't yet understand the bargain well enough, or Adelaide doesn't trust you.",
        },
        {
          k: "b",
          t: "Take Adelaide's place as Hollowmere's keeper.",
          to: "S4_END_02",
          major: true,
          req: { gte: { nerve: 4 } },
          lock: "You'd need far more nerve to stay.",
        },
        {
          k: "c",
          t: "Take Julian's hand and walk out together.",
          to: "S4_END_03",
          major: true,
          req: { gte: { "julian.affection": 4, "julian.trust": 3 } },
          lock: "Julian doesn't love or trust you enough to leave with you.",
        },
        {
          k: "d",
          t: "Run for the gates alone.",
          to: "S4_END_04",
          major: true,
        },
        {
          k: "e",
          t: "Let Mrs. Wren finish what she began.",
          to: "S4_END_05",
          major: true,
        },
      ],
    },
    {
      key: "S4_END_01",
      ch: 13,
      title: "The House That Let Go",
      ending: { n: 1, title: "The House That Let Go", type: "hopeful" },
      text: [
        "You break the bargain with nothing but a name and a song. Adelaide lifts her hands, and the nursery wall opens like a door onto a summer evening.",
        "ADELAIDE: Tell Julian I remember the rug. Tell him I never minded.",
        "The Hollow fights. It fails. It was never anything but hunger, and hunger can be shown a door.",
        when(
          { gte: { "julian.affection": 5 } },
          "In the morning Julian is sitting on the lawn, watching the east wing burn. He looks lighter than you've ever seen him. He offers you his scarred hand, and you take it.",
        ),
        when(
          { lte: { "julian.affection": 4 } },
          "In the morning Julian thanks you with tears in his eyes. He doesn't ask you to stay. You both know the house was the only thing holding you together.",
        ),
      ],
    },
    {
      key: "S4_END_02",
      ch: 13,
      title: "The New Keeper",
      ending: { n: 2, title: "The New Keeper", type: "dark" },
      text: [
        "You step into the circle of salt and say yes. The house shudders, satisfied, and is quiet for the first time in nine years.",
        "Adelaide is free. Julian is safe. Mrs. Wren retires to the village, white-haired and crying.",
        "You live in Hollowmere, and the house is very good to you. It fills your rooms with books. It lets the sun through the windows on the days you're sad.",
        when({ gte: { "julian.affection": 4 } }, "Julian visits each Sunday, bringing flowers. You never quite manage to tell him you aren't leaving."),
        "You don't age. You don't mind. You are the archivist now, and the archive is forever.",
      ],
    },
    {
      key: "S4_END_03",
      ch: 13,
      title: "Dawn on the Moor",
      ending: { n: 3, title: "Dawn on the Moor", type: "romance" },
      text: [
        "You take Julian's hand and walk out through the front doors, and the house does not stop you.",
        "Perhaps it has decided it can wait. Perhaps it has been outplayed. Perhaps, for one rare morning, hunger is outweighed by something better.",
        "You walk together across the moor as the sun breaks. Behind you, Hollowmere watches, patient.",
        when({ flags: ["comforted_adelaide"] }, "Adelaide's voice follows you to the road, quieter now, singing something new."),
        "JULIAN: I haven't been past the gate in nine years.",
        "YOU: Then let's go a little further.",
      ],
    },
    {
      key: "S4_END_04",
      ch: 13,
      title: "The One Who Left",
      ending: { n: 4, title: "The One Who Left", type: "bittersweet" },
      text: [
        "You run. The gravel hurts your feet. The gate is cold iron in your hands, and then it is behind you.",
        "You do not look back until you reach the road, and the house is just a house again: grey stone, black windows, a single light in the east wing.",
        "You survive. That is the truth of it. You survive, and you wonder for the rest of your life whether Julian ever got to stop playing.",
        when({ flags: ["answered_house"] }, "Some nights, in strange towns, you still hear your name called from a landing. You don't answer. You never answer."),
      ],
    },
    {
      key: "S4_END_05",
      ch: 13,
      title: "The Archivist",
      ending: { n: 5, title: "The Archivist", type: "dark" },
      text: [
        "You step back, and let Mrs. Wren do what she has been doing for nine years, what she hoped she would never have to do again.",
        "The house takes what it was promised, quietly and with enormous courtesy.",
        "Somewhere a piano plays. Somewhere a girl sings. Somewhere a young archivist is being hired, in a few years' time, by a very generous letter.",
        when({ flags: ["told_julian"] }, "Julian screams your name from the top of the stairs. The house closes that door first."),
        "Hollowmere is fed. Hollowmere remembers.",
      ],
    },
  ],
};
