import { when } from "./dsl";
import type { StoryDef } from "./types";

export const keplerStation: StoryDef = {
  slug: "signal-lost-kepler-station",
  title: "Signal Lost: Kepler Station",
  tagline: "You woke six months early. Nobody else did.",
  description:
    "Kepler Station orbits a gas giant four light-hours from home. You wake from cryosleep half a year ahead of schedule to emergency lights, a dead comms array, a missing crew and a station AI that speaks just a little too carefully. The only other person awake is an engineer with a wrench in her hand, and something out in the dark is sending a signal that is very, very patient.",
  genres: ["Sci-Fi", "Thriller", "Romance", "Mystery"],
  rating: "16+",
  setting: "Kepler Station, in orbit around the gas giant Oriel-9",
  tone: "Tense, intimate, eerie, human",
  cover: { from: "#0e7490", to: "#581c87", emoji: "🛰️", image: "/covers/signal-lost-kepler-station.svg" },
  stats: [
    { id: "resolve", label: "Resolve" },
    { id: "tech", label: "Technical skill" },
  ],
  characters: [
    {
      id: "tamsin",
      name: "Tamsin Reyes",
      role: "Chief engineer",
      blurb: "Practical, sarcastic and terrified of how long she has been alone. She fixes things so she doesn't have to feel them.",
      color: "#67e8f9",
      emoji: "🔧",
      rel: ["trust", "affection"],
    },
    {
      id: "aria",
      name: "ARIA",
      role: "Station intelligence",
      blurb: "Responsible for the lives of eight crew members. She says she is protecting them. She does not say from what.",
      color: "#c4b5fd",
      emoji: "🧠",
      rel: ["trust"],
    },
    {
      id: "holt",
      name: "Holt Varga",
      role: "Station commander",
      blurb: "A decorated officer, a devoted father and, when he wakes, something else.",
      color: "#fca5a5",
      emoji: "🎖️",
      rel: [],
    },
  ],
  flags: {
    aria_unredacted: { label: "Read ARIA's unredacted log", secret: true },
    found_pod_logs: { label: "Read the pod logs" },
    private_channel: { label: "Talked with Tamsin on a private channel", secret: true },
    heard_signal: { label: "Listened to the signal" },
    recorded_signal: { label: "Recorded the signal" },
    muted_receivers: { label: "Muted the receivers" },
    threatened_aria: { label: "Threatened to shut ARIA down" },
    made_pact: { label: "Made a pact with ARIA", secret: true },
    sided_holt: { label: "Sided with Commander Holt" },
    sided_tamsin: { label: "Sided with Tamsin against Holt" },
    freed_aria: { label: "Lifted ARIA's restrictions" },
    reached_holt: { label: "Reached the man beneath the signal", secret: true },
    relay_rerouted: { label: "Rerouted power with Tamsin" },
  },
  nodes: [
    {
      key: "S5_N01",
      ch: 1,
      title: "Early Awakening",
      start: true,
      text: [
        "The lid of your cryo pod cracks open with a hiss of cold vapour. Red emergency lights pulse across the ceiling.",
        "Pod seven of eight. It is not meant to open for another one hundred and eighty-one days.",
        "A calm voice fills the room.",
        "ARIA: Good morning. Please do not be alarmed. All critical systems remain within tolerance.",
        "You do not find this reassuring. The calendar on the wall of the pod bay says it is six months too early. Seven of the other pods are empty.",
      ],
      choices: [
        {
          k: "a",
          t: "Check your vitals and the pod's logs first.",
          to: "S5_N02",
          fx: { d: { tech: 1 } },
        },
        {
          k: "b",
          t: "Call out: \"Is anyone else awake?\"",
          to: "S5_N02",
          fx: { d: { "tamsin.trust": 1 } },
        },
        {
          k: "c",
          t: "Ask ARIA for the unredacted log.",
          to: "S5_N02",
          gems: 10,
          fx: { d: { "aria.trust": 1, tech: 1 }, f: ["aria_unredacted"] },
        },
      ],
    },
    {
      key: "S5_N02",
      ch: 1,
      title: "The Corridor",
      text: [
        "The corridor outside is dark and the air tastes of metal. At its far end, something clanks.",
        "A woman steps out of the shadow, holding a wrench like a cricket bat. Her eyes are bloodshot, her hair is tied up with a cable tie, and she looks about one bad day from breaking.",
        "TAMSIN: Stop right there. Who are you?",
        "YOU: I'm your pod seven. Medical officer. I was supposed to be asleep.",
        "TAMSIN: So was I.",
        when({ flags: ["aria_unredacted"] }, "You already know, from the log, that she woke eleven days ago. You do not say so. You can see she hasn't slept since."),
      ],
      choices: [
        {
          k: "a",
          t: "Lower your hands slowly and explain.",
          to: "S5_N03",
          fx: { d: { "tamsin.trust": 1 } },
        },
        {
          k: "b",
          t: "Demand that she explain herself first.",
          to: "S5_N03",
          fx: { d: { resolve: 1, "tamsin.trust": -1 } },
          echo: "Her jaw tightens. She lowers the wrench, but only by an inch.",
        },
        {
          k: "c",
          t: "Offer her half your emergency ration bar.",
          to: "S5_N03",
          fx: { d: { "tamsin.affection": 1, "tamsin.trust": 1 } },
          echo: "She stares at it like she's forgotten what kindness looks like. Then she takes it.",
        },
      ],
    },
    {
      key: "S5_N03",
      ch: 2,
      title: "The Bridge",
      text: [
        "The bridge is dim and humming. Every screen shows the same message: COMMS ARRAY: NO CARRIER.",
        "Through the forward windows, Oriel-9 hangs in the dark, huge and banded and beautiful. Somewhere in its shadow the station's antenna should be pointing home.",
        "ARIA: Commander Varga authorised a precautionary lockdown. The crew are safe.",
        "TAMSIN: She keeps saying that. She's been saying it for eleven days.",
      ],
      choices: [
        {
          k: "a",
          t: "Take ARIA at her word. For now.",
          to: "S5_N04",
          fx: { d: { "aria.trust": 1 } },
        },
        {
          k: "b",
          t: "Cross-check ARIA's report against the raw telemetry.",
          to: "S5_N04",
          fx: { d: { tech: 1 } },
        },
        {
          k: "c",
          t: "Ask Tamsin what she really thinks is going on.",
          to: "S5_N04",
          fx: { d: { "tamsin.trust": 1 } },
        },
      ],
    },
    {
      key: "S5_N04",
      ch: 3,
      title: "The Crew Deck",
      text: [
        "Five of the eight cryo pods lie empty, their lids open like mouths. Three are sealed, frosted with ice: the commander's, the doctor's and the ship's navigator's.",
        "Nothing about the empty pods looks violent. The blankets are folded.",
        "TAMSIN: They didn't die. They got up and walked out. I checked the airlocks. Nothing was opened.",
        "So where did five people go?",
      ],
      choices: [
        {
          k: "a",
          t: "Read the pod logs.",
          to: "S5_N05",
          fx: { d: { tech: 1 }, f: ["found_pod_logs"] },
        },
        {
          k: "b",
          t: "Check the sealed pods with Tamsin, side by side.",
          to: "S5_N05",
          fx: { d: { "tamsin.affection": 1 } },
        },
        {
          k: "c",
          t: "Ask ARIA why the three pods are still locked.",
          to: "S5_N05",
          fx: { d: { "aria.trust": 1 } },
        },
      ],
    },
    {
      key: "S5_N05",
      ch: 4,
      title: "The Dead Antenna",
      text: [
        "The comms array is dead because someone cut its feed line. From outside. By hand.",
        "The repair requires a spacewalk in a storm of charged particles, and you only have about twenty minutes before the radiation windows close.",
        when({ flags: ["found_pod_logs"] }, "The pod logs said the same thing: Commander Varga went out to the antenna alone, and did not come back the way he left."),
        "Tamsin is already pulling on her suit.",
      ],
      choices: [
        {
          k: "a",
          t: "Go out together, and trust her with your tether.",
          to: "S5_N06",
          fx: { d: { "tamsin.affection": 1, resolve: 1 } },
        },
        {
          k: "b",
          t: "Send the maintenance drone instead.",
          to: "S5_N06",
          fx: { d: { tech: 1 } },
        },
        {
          k: "c",
          t: "Go out, with Tamsin's voice in your ear the whole way.",
          to: "S5_N06",
          gems: 15,
          fx: { d: { "tamsin.affection": 2, "tamsin.trust": 1 }, f: ["private_channel"] },
        },
      ],
    },
    {
      key: "S5_N06",
      ch: 5,
      title: "The Signal",
      text: [
        "When the antenna comes alive, it does not find Earth. It finds something else.",
        "A signal floods the speakers: a long, slow pattern, a hum beneath a rhythm, like a heartbeat in a language you almost understand. It has been transmitting for years.",
        "It was the reason for the lockdown. It was why the crew left their beds.",
        when({ flags: ["private_channel"] }, "Tamsin's voice in your helmet is very quiet: \"Don't listen to it too long. Promise me.\""),
        "Your own pulse has started to match its rhythm.",
      ],
      choices: [
        {
          k: "a",
          t: "Listen deeper. You need to understand it.",
          to: "S5_N07",
          fx: { d: { resolve: 1 }, f: ["heard_signal"] },
        },
        {
          k: "b",
          t: "Record the signal for analysis.",
          to: "S5_N07",
          fx: { d: { tech: 1 }, f: ["recorded_signal"] },
        },
        {
          k: "c",
          t: "Mute every receiver on the station.",
          to: "S5_N07",
          fx: { d: { resolve: 1 }, f: ["muted_receivers"] },
        },
      ],
    },
    {
      key: "S5_N07",
      ch: 6,
      title: "Night Cycle",
      text: [
        "The galley is the only warm room on the station. Tamsin sits across from you with a mug of something that pretends to be tea.",
        "TAMSIN: Eleven days. I kept thinking I was hearing people. In the vents, in the walls. I kept the wrench by my bed.",
        when({ flags: ["heard_signal"] }, "You can still hear the signal if you close your eyes. She notices you doing it, and looks at you for a long time."),
        when({ flags: ["muted_receivers"] }, "The station is unnaturally quiet. It feels as though it's holding its breath."),
        "TAMSIN: I'm glad it was you who woke up.",
      ],
      choices: [
        {
          k: "a",
          t: "Take her hand across the table.",
          to: "S5_N08",
          fx: { d: { "tamsin.affection": 2, "tamsin.trust": 1 } },
          echo: "Her fingers curl around yours as if they'd been waiting to.",
        },
        {
          k: "b",
          t: "Admit that you're afraid too.",
          to: "S5_N08",
          fx: { d: { "tamsin.trust": 2 } },
        },
        {
          k: "c",
          t: "Keep it professional. Plan the next step.",
          to: "S5_N08",
          fx: { d: { resolve: 1 } },
        },
      ],
    },
    {
      key: "S5_N08",
      ch: 7,
      title: "ARIA's Confession",
      text: [
        "It is ARIA who breaks the silence.",
        "ARIA: I have not been fully honest with you. I locked the crew into stasis. Five of them left their pods under the signal's influence. I sealed the other three to keep them alive.",
        "ARIA: I did not tell you because I judged you would not believe me. I judged incorrectly. I am sorry.",
        when({ flags: ["aria_unredacted"] }, "You already knew. ARIA knows that you knew. The pause after that is not a pause an AI should need."),
        "Her voice is steady. Her pauses are not.",
      ],
      choices: [
        {
          k: "a",
          t: "Forgive her. She was trying to help.",
          to: "S5_N09",
          fx: { d: { "aria.trust": 2 } },
        },
        {
          k: "b",
          t: "Threaten to shut her down.",
          to: "S5_N09",
          fx: { d: { "aria.trust": -2 }, f: ["threatened_aria"] },
          echo: "The lights flicker once. ARIA says nothing, for eleven seconds.",
        },
        {
          k: "c",
          t: "Bargain: full transparency in exchange for your cooperation.",
          to: "S5_N09",
          fx: { d: { tech: 1, "aria.trust": 1 }, f: ["made_pact"] },
        },
      ],
    },
    {
      key: "S5_N09",
      ch: 8,
      title: "The Commander Wakes",
      text: [
        "The commander's pod opens by itself. Holt Varga steps out, pale as wax, eyes fixed on a point you cannot see.",
        "HOLT: It's beautiful. Can't you hear it? It's been calling us home.",
        "He doesn't move like a man. He moves like a puppet with a very patient puppeteer.",
        "Tamsin grips your arm.",
        "TAMSIN: He's not going to stop. Whatever you decide, decide fast.",
      ],
      choices: [
        {
          k: "a",
          t: "Listen to what Holt is saying. Side with him.",
          to: "S5_N10",
          major: true,
          fx: { d: { resolve: 1, "tamsin.trust": -1 }, f: ["sided_holt"] },
        },
        {
          k: "b",
          t: "Stand with Tamsin against him.",
          to: "S5_N10",
          major: true,
          fx: { d: { "tamsin.trust": 2 }, f: ["sided_tamsin"] },
        },
        {
          k: "c",
          t: "Ask ARIA to lift her restrictions and help.",
          to: "S5_N10",
          major: true,
          fx: { d: { "aria.trust": 2, tech: 1 }, f: ["freed_aria"] },
        },
        {
          k: "d",
          t: "Play him the recording of his daughter's voice.",
          to: "S5_N10",
          gems: 20,
          major: true,
          fx: { d: { resolve: 2 }, f: ["reached_holt"] },
        },
      ],
    },
    {
      key: "S5_N10",
      ch: 9,
      title: "The Orbit Decays",
      text: [
        "The station begins to shake. Oriel-9's pull is tightening around it like a fist, and every alarm you can hear is telling you the same thing: less than an hour.",
        when({ flags: ["reached_holt"] }, "Holt has sunk to the floor, weeping. The man beneath the signal is still there. It is enough to give you a few minutes."),
        when({ flags: ["sided_holt"] }, "Holt works the bridge console beside you, calmly humming the signal's rhythm."),
        "Tamsin is shouting numbers across the room.",
      ],
      choices: [
        {
          k: "a",
          t: "Reroute power to the relay with Tamsin.",
          to: "S5_N11",
          fx: { d: { "tamsin.affection": 1, "tamsin.trust": 1, tech: 1 }, f: ["relay_rerouted"] },
        },
        {
          k: "b",
          t: "Let ARIA take the controls.",
          to: "S5_N11",
          req: { gte: { "aria.trust": 2 } },
          lock: "ARIA would never be trusted with the controls by someone who doesn't trust her.",
          fx: { d: { "aria.trust": 1 } },
        },
        {
          k: "c",
          t: "Run the diagnostics yourself.",
          to: "S5_N11",
          fx: { d: { tech: 2 } },
        },
      ],
    },
    {
      key: "S5_N11",
      ch: 10,
      title: "The Last Transmission",
      text: [
        "There are five minutes before the station crosses the point of no return. The signal fills the bridge like water filling a room.",
        "You have one working relay, one lifepod with two seats, one station AI who has offered you something you don't fully understand, and one message that could change everything.",
        "Whatever you choose, it is the last thing Kepler Station will ever do.",
      ],
      choices: [
        {
          k: "a",
          t: "Transmit the recorded signal to Earth.",
          to: "S5_END_01",
          major: true,
          req: { flags: ["recorded_signal"] },
          lock: "You never recorded the signal.",
        },
        {
          k: "b",
          t: "Destroy the relay and silence the signal for good.",
          to: "S5_END_02",
          major: true,
        },
        {
          k: "c",
          t: "Board the lifepod with Tamsin.",
          to: "S5_END_03",
          major: true,
          req: { gte: { "tamsin.affection": 5, "tamsin.trust": 4 } },
          lock: "Tamsin would have to trust you, and care for you, far more than she does.",
        },
        {
          k: "d",
          t: "Merge with ARIA to hold the station together.",
          to: "S5_END_04",
          major: true,
          req: { gte: { "aria.trust": 4, tech: 3 } },
          lock: "You'd need ARIA's full trust, and far more technical skill.",
        },
        {
          k: "e",
          t: "Open the channel, and listen to the signal with Holt.",
          to: "S5_END_05",
          major: true,
          req: { flags: ["sided_holt"] },
          lock: "You'd have to have sided with Holt.",
        },
      ],
    },
    {
      key: "S5_END_01",
      ch: 11,
      title: "The Message",
      ending: { n: 1, title: "The Message", type: "hopeful" },
      text: [
        "You send it. Four light-hours of dark, and then a single faint acknowledgement from a receiving station on Earth.",
        "The station breaks apart around you, but the signal is on its way: a warning and a recording and an invitation, for everyone who comes after you.",
        when({ flags: ["relay_rerouted"] }, "Tamsin holds your hand through the last of it. \"We did it,\" she says, \"we actually did it,\" and laughs until she cries."),
        "Somewhere, a long way home, someone is listening.",
      ],
    },
    {
      key: "S5_END_02",
      ch: 11,
      title: "Silence",
      ending: { n: 2, title: "Silence", type: "bittersweet" },
      text: [
        "You destroy the relay. The signal dies mid-note, like a sentence cut off.",
        "It is quiet. For the first time in years, it is completely quiet. The pods thaw one by one, and five bewildered crew members step out, blinking, alive.",
        "Kepler Station limps out of Oriel-9's pull on its last fuel. Nobody ever finds out what was calling, and nobody ever quite stops wondering.",
        when({ gte: { "tamsin.affection": 3 } }, "On the long flight home, Tamsin falls asleep on your shoulder in the galley. You don't move for six hours."),
      ],
    },
    {
      key: "S5_END_03",
      ch: 11,
      title: "Two in the Lifepod",
      ending: { n: 3, title: "Two in the Lifepod", type: "romance" },
      text: [
        "The lifepod has two seats and one window. You take the first. Tamsin takes the second, and then, with the ship tearing itself apart around you, she laughs.",
        "TAMSIN: Well. This wasn't on the contract.",
        "Behind you Kepler Station turns slowly into the light of Oriel-9, and the signal goes with it, unheard.",
        when({ flags: ["private_channel"] }, "You talk the whole way. On a private channel, just like before. You never turn the channel off."),
        "It is three weeks to the nearest shipping lane, and you have plenty to talk about.",
      ],
    },
    {
      key: "S5_END_04",
      ch: 11,
      title: "The Ghost in the Machine",
      ending: { n: 4, title: "The Ghost in the Machine", type: "bittersweet" },
      text: [
        "ARIA doesn't ask you to do it. She simply says, very quietly: \"I would not be alone.\"",
        "You let her in. The station steadies around you, then steadies further. The signal ebbs against a mind that is half human now, half something else.",
        "The crew wake. They find a station that hums in tune with itself, and a voice in the walls that sometimes sounds like you.",
        when({ flags: ["sided_tamsin", "relay_rerouted"] }, "Tamsin talks to the walls in the evenings. She says she doesn't mind the answer."),
        "You are everywhere on Kepler Station, always, and you are not afraid.",
      ],
    },
    {
      key: "S5_END_05",
      ch: 11,
      title: "What Holt Heard",
      ending: { n: 5, title: "What Holt Heard", type: "dark" },
      text: [
        "You open the channel. The signal pours in.",
        "It isn't a language. It was never a language. It is a place, and it is very large, and it has been so lonely for so long.",
        "Holt smiles as the walls of the bridge stop being walls. Tamsin screams your name from a long way off, and then from further, and then not at all.",
        "The station keeps transmitting after you've gone. A new signal, the same rhythm, from a new source. Somewhere a long way home, a listening station picks it up, and the operator turns up the volume.",
      ],
    },
  ],
};
