import { when } from "./dsl";
import type { StoryDef } from "./types";

export const lastTrain: StoryDef = {
  slug: "last-train-to-bellweather",
  title: "The Last Train to Bellweather",
  tagline: "A train that stopped running twenty-three years ago. A passenger list with your name on it.",
  description:
    "Three months after your grandmother's death, you return to the small town of Bellweather to sell her abandoned bookshop. On your first night the station clock strikes midnight, a train slides onto Platform Three, and a conductor named Rowan Vale steps down holding a manifest that lists you as a passenger. The date beside your name is tomorrow.",
  genres: ["Romance", "Mystery", "Supernatural"],
  rating: "16+",
  setting: "Bellweather, a rain-soaked market town with a haunted railway",
  tone: "Cinematic, emotional, eerie, slow-burn romance",
  cover: { from: "#0f766e", to: "#1e1b4b", emoji: "🚂", image: "/covers/the-last-train-to-bellweather.jpg" },
  stats: [
    { id: "courage", label: "Courage" },
    { id: "mystery", label: "Insight" },
  ],
  characters: [
    {
      id: "rowan",
      name: "Rowan Vale",
      role: "The midnight conductor",
      blurb: "Guarded, dry-witted and quietly frightened. He has been collecting other people's last journeys for a very long time.",
      color: "#5eead4",
      emoji: "🎩",
      rel: ["trust", "affection"],
    },
    {
      id: "violet",
      name: "Violet",
      role: "The child on Platform Three",
      blurb: "She drowned in the Great Flood thirty years ago. Your grandmother promised she would not be forgotten.",
      color: "#c4b5fd",
      emoji: "🕯️",
      rel: ["bond"],
    },
    {
      id: "mara",
      name: "Mara Wells",
      role: "Your grandmother",
      blurb: "Bookseller, keeper of secrets. She spent twenty-three years searching for the one book that could undo her greatest mistake.",
      color: "#fcd34d",
      emoji: "📚",
      rel: [],
    },
    {
      id: "stationmaster",
      name: "The Stationmaster",
      role: "Keeper of the clocks",
      blurb: "He has been in Bellweather longer than the railway. He says the town is only borrowing time.",
      color: "#fca5a5",
      emoji: "⏳",
      rel: [],
    },
  ],
  flags: {
    old_ticket: { label: "Carries a ticket with your name" },
    saw_manifest: { label: "Read the passenger manifest", secret: true },
    opened_hidden_compartment: { label: "Opened the hidden compartment", secret: true },
    read_notebook: { label: "Read Mara's notebook" },
    hid_notebook: { label: "Hid the notebook from Rowan", secret: true },
    believed_rowan: { label: "Believed Rowan" },
    lied_to_rowan: { label: "Called Rowan a liar" },
    followed_townsfolk: { label: "Followed the whispering townsfolk", secret: true },
    learned_mara_secret: { label: "Learned what Mara changed", secret: true },
    saved_violet: { label: "Took Violet's hand" },
    restored_years: { label: "Began restoring the stolen years" },
    confronted_stationmaster: { label: "Questioned the Stationmaster", secret: true },
    years_returned_fully: { label: "Let the years return completely" },
    told_rowan_clock: { label: "Told Rowan about his clock" },
    broke_clock: { label: "Broke Rowan's clock" },
    held_his_hand: { label: "Held Rowan's hand as it broke", secret: true },
    made_amends: { label: "Apologised to Rowan" },
  },
  items: { old_ticket: "Old ticket" },
  nodes: [
    {
      key: "S1_N01",
      ch: 1,
      title: "The Midnight Train",
      start: true,
      text: [
        "The station is empty. Rain taps against the glass roof.",
        "Then the clock strikes twelve.",
        "A distant horn cuts through the darkness, and a train slides silently onto Platform Three. There hasn't been a train here since you were a child.",
        "The doors open. A man in a dark conductor's coat steps down and studies you for several seconds.",
        "ROWAN: You shouldn't be here.",
        "YOU: Neither should that train.",
        "For the first time, Rowan looks frightened.",
        "ROWAN: What name did you give at the station?",
      ],
      choices: [
        {
          k: "a",
          t: "\"I didn't give anyone my name.\"",
          to: "S1_N02A",
          fx: { d: { courage: 1, "rowan.trust": 1 } },
          echo: "Something in his shoulders loosens. He believes you.",
        },
        {
          k: "b",
          t: "\"Why? What's on the passenger list?\"",
          to: "S1_N02B",
          fx: { d: { mystery: 1 } },
        },
        {
          k: "c",
          t: "\"Show me the passenger list.\"",
          to: "S1_N02C",
          gems: 15,
          fx: { d: { mystery: 2, "rowan.trust": 1 }, f: ["saw_manifest"] },
        },
      ],
    },
    {
      key: "S1_N02A",
      ch: 1,
      title: "The Conductor",
      text: [
        "Rowan steps closer. Up close he looks no older than thirty, and far more tired than that.",
        "ROWAN: You have your grandmother's eyes.",
        "Your stomach tightens.",
        "YOU: You knew her?",
        "He looks away.",
        "ROWAN: Everyone knew Mara.",
        "He turns toward the train. A folded paper falls from his coat, and you catch it before it touches the ground.",
        "It is a ticket. Your name is printed across the top in old-fashioned type.",
      ],
      next: "S1_N03",
      fx: { f: ["old_ticket"], i: ["old_ticket"] },
    },
    {
      key: "S1_N02B",
      ch: 1,
      title: "The Manifest",
      text: [
        "You ask again about the passenger list. Rowan doesn't answer, but his fingers tighten on the brass clipboard under his arm.",
        "YOU: Why is my name on it?",
        "He freezes.",
        "ROWAN: It shouldn't be.",
        "There are dozens of names beneath yours. Every one has a date beside it, and many of those dates are decades old.",
        "After a long moment he tears a ticket from the bottom of the page and presses it into your palm.",
        "ROWAN: Keep it. You'll want proof that you didn't imagine this.",
      ],
      next: "S1_N03",
      fx: { f: ["old_ticket"], i: ["old_ticket"] },
    },
    {
      key: "S1_N02C",
      ch: 1,
      title: "The Hidden Passenger",
      text: [
        "Rowan reluctantly turns the clipboard toward you.",
        "You see your name. Then, three lines above it, another.",
        "MARA WELLS.",
        "Your grandmother. The date beside her name is tonight.",
        "YOU: My grandmother died three months ago.",
        "ROWAN: I know.",
        "YOU: How?",
        "Rowan doesn't answer. But he doesn't look surprised that you asked, either, and that is somehow worse.",
      ],
      next: "S1_N03",
    },
    {
      key: "S1_N03",
      ch: 2,
      title: "The Bellweather Clock",
      text: [
        "The station lights flicker. The giant clock above Platform Three moves backwards by one minute. Then another. Then another.",
        "Rowan grabs your wrist.",
        "ROWAN: We need to leave. Now.",
        when({ flags: ["old_ticket"] }, "In your pocket, the ticket has turned warm, as though someone were holding it from the other side."),
        when({ flags: ["saw_manifest"] }, "You think of your grandmother's name and the date beside it, and your feet feel very far away from you."),
      ],
      choices: [
        {
          k: "a",
          t: "Trust Rowan and leave with him.",
          to: "S1_N04A",
          fx: { d: { "rowan.trust": 1 } },
        },
        {
          k: "b",
          t: "Pull your hand away. \"I'm not going anywhere.\"",
          to: "S1_N04B",
          fx: { d: { courage: 1, "rowan.trust": -1 } },
          echo: "Rowan lets go. The hurt in his face is gone almost before you see it.",
        },
      ],
    },
    {
      key: "S1_N04A",
      ch: 3,
      title: "The Bookshop",
      text: [
        "Rowan leads you through the rain to your grandmother's bookshop. Inside, every clock has stopped at twelve.",
        "He studies the shelves the way someone studies a face they haven't seen in years.",
        "ROWAN: Your grandmother was looking for something.",
        "YOU: What?",
        "ROWAN: The Bellweather Ledger.",
        "You remember seeing those words underlined three times in one of her notebooks.",
      ],
      next: "S1_N04C",
    },
    {
      key: "S1_N04B",
      ch: 3,
      title: "The Platform",
      text: [
        "You refuse to leave. The platform trembles, and for a fraction of a second the train windows show people sitting inside.",
        "Not passengers. People you recognise from old family photographs: a great-aunt, a man with your mother's chin, a little girl in a yellow raincoat.",
        "Then everything is ordinary again.",
        "Rowan looks at you across the empty platform.",
        "ROWAN: Now do you believe me?",
        "He doesn't wait for an answer. At dawn you find yourself walking to the bookshop, and he is following twenty paces behind, pretending not to.",
      ],
      next: "S1_N04C",
    },
    {
      key: "S1_N04C",
      ch: 3,
      title: "Mara's Notebook",
      text: [
        "On the counter, under a teacup with a crescent of dried lipstick, lies your grandmother's last notebook. The final entry is dated the night she died.",
        "> If anything happens to me: the Ledger is behind the false shelf. Do not let the Stationmaster see it. Do not let Rowan take the blame.",
        when({ flags: ["old_ticket"] }, "The ticket in your pocket is the same shade of cream as the notebook's pages."),
        "Rowan hovers near the door. He has read the handwriting over your shoulder, or pretends he hasn't.",
      ],
      choices: [
        {
          k: "a",
          t: "Read the notebook carefully, page by page.",
          to: "S1_N05",
          fx: { d: { mystery: 1 }, f: ["read_notebook"] },
        },
        {
          k: "b",
          t: "Ask Rowan to read it with you.",
          to: "S1_N05",
          fx: { d: { "rowan.trust": 1, "rowan.affection": 1 }, f: ["read_notebook"] },
          echo: "He sits beside you, close enough that you can hear him breathe.",
        },
        {
          k: "c",
          t: "Slip it into your coat before he can see more.",
          to: "S1_N05",
          fx: { d: { mystery: 1, "rowan.trust": -1 }, f: ["read_notebook", "hid_notebook"] },
          echo: "You tell yourself it's only for now.",
        },
      ],
    },
    {
      key: "S1_N05",
      ch: 4,
      title: "The Hidden Compartment",
      text: [
        "Behind a loose shelf you find a locked compartment, its brass lock green with age.",
        when({ flags: ["hid_notebook"] }, "You can feel the notebook's weight against your ribs. Rowan hasn't asked. That's almost worse."),
        when({ gte: { "rowan.trust": 2 } }, "Rowan crouches next to you without being asked. He has done this before, you realise. Helped someone search."),
      ],
      choices: [
        {
          k: "a",
          t: "Search the shop for another way inside.",
          to: "S1_N06",
          fx: { d: { mystery: 1 } },
        },
        {
          k: "b",
          t: "Ask Rowan for help.",
          to: "S1_N06",
          fx: { d: { "rowan.trust": 1, "rowan.affection": 1 } },
        },
        {
          k: "c",
          t: "Let Rowan break the lock — and ask him why he knows how.",
          to: "S1_N06",
          gems: 15,
          fx: { d: { mystery: 2, "rowan.trust": 2, "rowan.affection": 1 }, f: ["opened_hidden_compartment"] },
        },
      ],
    },
    {
      key: "S1_N06",
      ch: 4,
      title: "The Ledger",
      text: [
        "Inside is an enormous leather book. Every page carries the same sentence, in your grandmother's handwriting and in a dozen others:",
        "> Bellweather remembers what the living choose to forget.",
        "The final pages contain names. One of them is Rowan's. His death date is tomorrow.",
        when({ flags: ["saw_manifest"] }, "You recognise the same small symbol beside Rowan's name that you saw beside your own on the manifest."),
        when({ flags: ["old_ticket"] }, "The ticket in your pocket begins to glow, faintly, in time with your pulse."),
        when({ flags: ["opened_hidden_compartment"] }, "Beneath the Ledger lies a folded map of the tunnels under the station, marked in your grandmother's hand."),
      ],
      next: "S1_N07",
    },
    {
      key: "S1_N07",
      ch: 5,
      title: "Rowan's Secret",
      text: [
        "YOU: You're going to die tomorrow.",
        "Rowan goes silent. Eventually he speaks.",
        "ROWAN: I already did.",
        "He explains: every midnight train carries people who were meant to die, but whose deaths were changed by someone in Bellweather. The town has been borrowing time. Someone has been rewriting the past, and the train is what collects the debt.",
        "ROWAN: I'm the one who has to punch the tickets.",
      ],
      choices: [
        {
          k: "a",
          t: "Believe him.",
          to: "S1_N07B",
          major: true,
          fx: { d: { "rowan.trust": 2 }, f: ["believed_rowan"] },
          echo: "He exhales like a man who has been holding his breath for twenty-three years.",
        },
        {
          k: "b",
          t: "Accuse him of lying.",
          to: "S1_N07B",
          major: true,
          fx: { d: { "rowan.trust": -2 }, f: ["lied_to_rowan"] },
          echo: "Rowan nods slowly, as though he had expected nothing else.",
        },
      ],
    },
    {
      key: "S1_N07B",
      ch: 6,
      title: "A Day in Bellweather",
      text: [
        "Daylight makes the town look almost innocent. Bakers open their shutters. Children cross the square with umbrellas.",
        "But the townspeople glance at you a beat too long. They go quiet when you pass.",
        when({ flags: ["believed_rowan"] }, "Rowan walks beside you in the daylight, which you suspect he isn't supposed to be able to do."),
        when({ flags: ["lied_to_rowan"] }, "Rowan keeps his distance, hands in his pockets. He hasn't said a word since you called him a liar."),
        "You have one whole day before the next midnight.",
      ],
      choices: [
        {
          k: "a",
          t: "Dig through the parish archive.",
          to: "S1_N08",
          fx: { d: { mystery: 2 } },
        },
        {
          k: "b",
          t: "Follow Mara's marginal notes through the archive.",
          to: "S1_N08",
          req: { gte: { mystery: 3 }, flags: ["read_notebook"] },
          lock: "You don't know enough yet to read her shorthand.",
          fx: { d: { mystery: 1 }, f: ["learned_mara_secret"] },
          echo: "Her handwriting begins to make terrible, simple sense.",
        },
        {
          k: "c",
          t: "Walk the river path with Rowan.",
          to: "S1_N08",
          req: { gte: { "rowan.trust": 1 } },
          lock: "Rowan isn't ready to be alone with you.",
          fx: { d: { "rowan.affection": 2, "rowan.trust": 1 } },
          echo: "He almost laughs, once, at something you say. He looks startled by it.",
        },
        {
          k: "d",
          t: "Follow the townspeople who keep whispering.",
          to: "S1_N08",
          fx: { d: { courage: 1 }, f: ["followed_townsfolk"] },
        },
      ],
    },
    {
      key: "S1_N08",
      ch: 7,
      title: "The Child in the Station",
      text: [
        "The following night you return to the station. A little girl is standing alone on Platform Three in a yellow raincoat.",
        "You recognise her from a photograph in your grandmother's house. Her name is Violet. She drowned thirty years ago.",
        when({ flags: ["followed_townsfolk"] }, "The whispers you followed this afternoon led to a shrine at the edge of the square: a hundred yellow ribbons, tied in memory of a girl."),
        "VIOLET: You're Mara's granddaughter.",
        "YOU: How do you know me?",
        "VIOLET: Because she told me you would come.",
      ],
      choices: [
        {
          k: "a",
          t: "Take Violet's hand.",
          to: "S1_N09",
          fx: { d: { courage: 1, "violet.bond": 2 }, f: ["saved_violet"] },
        },
        {
          k: "b",
          t: "Call Rowan before doing anything.",
          to: "S1_N09",
          req: { gte: { "rowan.trust": 2 } },
          lock: "Rowan would have to trust you enough to come when called.",
          fx: { d: { "rowan.trust": 1, "rowan.affection": 1, "violet.bond": 1 } },
        },
        {
          k: "c",
          t: "Ask Violet what your grandmother changed.",
          to: "S1_N09",
          gems: 20,
          fx: { d: { mystery: 2, "violet.bond": 1 }, f: ["learned_mara_secret"] },
        },
      ],
    },
    {
      key: "S1_N09",
      ch: 8,
      title: "The Tunnel of Clocks",
      text: [
        "Violet reveals a hidden door underneath Platform Three. Beyond it a tunnel stretches into the dark, lined with clocks, every one showing a different year.",
        "At the end stands the original Bellweather Stationmaster, exactly as tall and patient as Violet described.",
        "STATIONMASTER: The town can be saved. But someone must return every stolen year.",
        "That means sending every borrowed life back to where it belongs.",
        "Rowan refuses.",
        "ROWAN: There has to be another way.",
      ],
      choices: [
        {
          k: "a",
          t: "Search for another solution.",
          to: "S1_N10A",
          fx: { d: { mystery: 1, "rowan.affection": 1 } },
        },
        {
          k: "b",
          t: "Restore the stolen years immediately.",
          to: "S1_N10B",
          major: true,
          fx: { d: { courage: 2 }, f: ["restored_years"] },
        },
        {
          k: "c",
          t: "Ask the Stationmaster who borrowed the years in the first place.",
          to: "S1_N10A",
          req: { gte: { mystery: 3 } },
          lock: "You don't know enough to ask the right question.",
          fx: { d: { mystery: 1 }, f: ["confronted_stationmaster"] },
        },
      ],
    },
    {
      key: "S1_N10A",
      ch: 9,
      title: "The Broken Clock",
      text: [
        "One clock is different. It doesn't belong to Bellweather. It is small, dented, and has a conductor's ticket-punch hung beside it.",
        "It is Rowan's.",
        when({ flags: ["confronted_stationmaster"] }, "The Stationmaster's voice is thin. \"Break it and he is free. He'll also forget everything he ever was. I did not make the rules; I only keep them.\""),
        "The glass can be broken. But breaking it means Rowan will lose every memory of you.",
      ],
      choices: [
        {
          k: "a",
          t: "Tell Rowan what you've discovered.",
          to: "S1_N11",
          fx: { d: { "rowan.trust": 2 }, f: ["told_rowan_clock"] },
        },
        {
          k: "b",
          t: "Break the clock — quietly, alone.",
          to: "S1_N11",
          major: true,
          fx: { f: ["broke_clock"] },
          echo: "The glass shivers. Somewhere, a door closes that you will not be able to open again.",
        },
        {
          k: "c",
          t: "Break the clock while holding Rowan's hand.",
          to: "S1_N11",
          gems: 25,
          major: true,
          fx: { d: { "rowan.affection": 2 }, f: ["broke_clock", "held_his_hand"] },
        },
      ],
    },
    {
      key: "S1_N10B",
      ch: 9,
      title: "The Choice",
      text: [
        "The clocks begin to move. One by one the tunnel fills with the sound of years being returned.",
        "Violet starts to fade, like breath on a window.",
        "Rowan reaches for you.",
        "ROWAN: You can still stop it. But you have to decide now.",
      ],
      choices: [
        {
          k: "a",
          t: "Let the years return completely.",
          to: "S1_N11",
          major: true,
          fx: { d: { courage: 1 }, f: ["years_returned_fully"] },
        },
        {
          k: "b",
          t: "Stop the process.",
          to: "S1_N11",
          major: true,
          fx: { d: { "rowan.trust": -2 }, rf: ["restored_years"] },
          echo: "The clocks stutter. Rowan looks at you like he has lost something he never quite had.",
        },
      ],
    },
    {
      key: "S1_N11",
      ch: 10,
      title: "The Final Train",
      text: [
        "Everything begins collapsing. The tunnel trembles, plaster rains from the ceiling, and the clocks strike thirteen, fourteen, fifteen.",
        when(
          { flags: ["broke_clock"] },
          "Rowan's clock is a scatter of glass at your feet. He is alive — more alive than you have ever seen him. He looks at you with kind, empty curiosity.",
          "ROWAN: I don't know why, but I feel like I've known you forever.",
        ),
        when(
          { flags: ["restored_years"] },
          "The dead begin disappearing into the light, one by one. Violet smiles before she vanishes.",
        ),
        when(
          { flags: ["saved_violet"], notFlags: ["restored_years"] },
          "Violet refuses to let go of your hand. \"I can guide them,\" she says. \"I know where they all belong.\"",
        ),
        "The train waits at the end of the tunnel with its doors open.",
      ],
      next: "S1_R11",
    },
    {
      key: "S1_R11",
      ch: 10,
      title: "",
      text: [],
      routes: [{ if: { flags: ["lied_to_rowan"], notFlags: ["made_amends"] }, to: "S1_N11X" }, { to: "S1_N12" }],
    },
    {
      key: "S1_N11X",
      ch: 10,
      title: "The Thing You Said",
      text: [
        "Rowan stops at the train doors.",
        "ROWAN: You called me a liar. In the bookshop. I've been thinking about it ever since.",
        when({ flags: ["broke_clock"] }, "Even through the fog of forgotten years, something in his eyes remembers that accusation."),
        "ROWAN: I'm not angry. I just need to know if you meant it. Because what I'm about to ask you to trust me with is very large.",
      ],
      choices: [
        {
          k: "a",
          t: "Apologise — and mean it.",
          to: "S1_N12",
          fx: { d: { "rowan.trust": 2 }, f: ["made_amends"] },
          echo: "He nods once. It isn't forgiveness yet. It's the door to it.",
        },
        {
          k: "b",
          t: "\"I had every reason to doubt you.\"",
          to: "S1_N12",
          fx: { d: { "rowan.trust": -1 } },
        },
      ],
    },
    {
      key: "S1_N12",
      ch: 11,
      title: "The Final Decision",
      text: [
        "The Stationmaster lifts his lantern. The platform, the tunnel and the night all seem to hold still.",
        "STATIONMASTER: One last choice, Mara's granddaughter. The train takes someone tonight. Or it takes nothing, and everything.",
        when({ gte: { "rowan.affection": 5, "rowan.trust": 4 } }, "Rowan's hand finds yours without looking. It is the most natural thing in the world."),
        when({ lte: { "rowan.trust": 1 } }, "Rowan stands a careful arm's length away."),
      ],
      choices: [
        {
          k: "a",
          t: "Save Rowan.",
          to: "S1_END_01",
          major: true,
          req: { gte: { "rowan.affection": 5, "rowan.trust": 4 } },
          lock: "Rowan would need to trust you and love you more than he does now.",
        },
        {
          k: "b",
          t: "Save Bellweather.",
          to: "S1_END_02",
          major: true,
          req: { gte: { mystery: 4 } },
          lock: "You don't understand the town's bargain well enough to rewrite it.",
        },
        {
          k: "c",
          t: "Take Rowan's place.",
          to: "S1_END_03",
          major: true,
          req: { gte: { courage: 4 } },
          lock: "You'd need far more courage than you've shown so far.",
        },
        {
          k: "d",
          t: "Break the system completely.",
          to: "S1_END_04",
          major: true,
          req: { flags: ["broke_clock", "learned_mara_secret"] },
          lock: "You'd have to know Mara's secret and have broken the first clock.",
        },
        {
          k: "e",
          t: "Step back and let the train choose.",
          to: "S1_END_05",
          major: true,
        },
      ],
    },
    {
      key: "S1_END_01",
      ch: 12,
      title: "The Two Who Remembered",
      ending: { n: 1, title: "The Two Who Remembered", type: "romance" },
      text: [
        "Rowan survives. Bellweather loses its supernatural connection, and the clocks in your grandmother's shop begin to tick again.",
        "Months later, you reopen the bookshop. One rainy evening the bell above the door rings.",
        "Rowan places a train ticket on the counter.",
        "ROWAN: I don't remember the train.",
        "He smiles.",
        "ROWAN: But I remember you.",
        when({ flags: ["broke_clock"] }, "Somewhere in the walls, the last glass fragment of his clock hums a note, and stops."),
      ],
    },
    {
      key: "S1_END_02",
      ch: 12,
      title: "Bellweather Remembers",
      ending: { n: 2, title: "Bellweather Remembers", type: "bittersweet" },
      text: [
        "The stolen years return. The town survives. The supernatural train vanishes from the timetable as if it had never existed.",
        "Rowan watches from the platform. He knows you saved everyone. He also knows you chose the town over him.",
        when(
          { gte: { "rowan.affection": 5 } },
          "ROWAN: I'd have made the same choice. I'd have hated you a little for it, and loved you for it more.",
          "He kisses your forehead like a goodbye that could still become something else.",
        ),
        when(
          { lte: { "rowan.affection": 4 } },
          "He touches his cap, a conductor's farewell, and walks into the morning light alone.",
        ),
      ],
    },
    {
      key: "S1_END_03",
      ch: 12,
      title: "The New Conductor",
      ending: { n: 3, title: "The New Conductor", type: "bittersweet" },
      text: [
        "You take Rowan's place. The train leaves Bellweather with you at the door, and every midnight you carry the memories of the dead.",
        "Rowan remains in the living world. Sometimes, when the train stops at the old station, you see him waiting on the platform.",
        when({ flags: ["saved_violet"] }, "Violet rides beside you in her yellow raincoat, telling every passenger where they belong."),
        "Neither of you ever says goodbye.",
      ],
    },
    {
      key: "S1_END_04",
      ch: 12,
      title: "The End of Midnight",
      ending: { n: 4, title: "The End of Midnight", type: "hopeful" },
      text: [
        "You destroy the clock. The train disappears. Every stolen memory returns to its rightful owner, and the supernatural cycle ends permanently.",
        "Violet's final message appears in your grandmother's notebook:",
        "> Some stories survive because someone remembers.",
        when({ gte: { "rowan.affection": 7 } }, "Rowan stays. He doesn't know why he knows your name. He keeps knowing it anyway, every morning, at the bookshop counter."),
        when({ lte: { "rowan.affection": 6 } }, "Rowan leaves Bellweather after the events of that night. You find a single ticket in the post a year later: a platform, a date, and no return."),
      ],
    },
    {
      key: "S1_END_05",
      ch: 12,
      title: "The Last Passenger",
      ending: { n: 5, title: "The Last Passenger", type: "dark" },
      text: [
        "You step back. The train waits. The clocks strike, and strike, and strike.",
        "Nobody chooses. The night simply continues the way it has for twenty-three years.",
        "You wake in the bookshop at dawn with a ticket in your hand. The date on it is tomorrow, and the name on it is yours.",
        "Bellweather remembers what the living choose to forget.",
        when({ flags: ["lied_to_rowan"] }, "Across the square, Rowan is watching the shop. He doesn't come in."),
      ],
    },
  ],
};
