import { when } from "./dsl";
import type { StoryDef } from "./types";

export const lemonTarts: StoryDef = {
  slug: "love-lies-and-lemon-tarts",
  title: "Love, Lies & Lemon Tarts",
  tagline: "Eight bakers. One trophy. One extremely annoying man who keeps stealing your vanilla.",
  description:
    "You've made it into The Great Crumb & Whisk, Britain's most beloved (and most dramatic) baking competition, armed with your late grandmother's recipe notebook and a deep fear of live television. Your rival is Jun Park, who is infuriatingly talented, unfairly handsome and, apparently, hoarding all the good vanilla. Somebody is also sabotaging the bakes. Everyone is a suspect. Mostly the soufflé.",
  genres: ["Comedy", "Romance", "Slice of Life"],
  rating: "13+",
  setting: "The Great Crumb & Whisk tent, somewhere in the English countryside",
  tone: "Warm, silly, fast and flirty, with a real heart underneath",
  cover: { from: "#f59e0b", to: "#be185d", emoji: "🍋", image: "/covers/love-lies-lemon-tarts.svg" },
  stats: [
    { id: "creativity", label: "Creativity" },
    { id: "poise", label: "Poise" },
  ],
  characters: [
    {
      id: "jun",
      name: "Jun Park",
      role: "Your insufferable, brilliant rival",
      blurb: "A software engineer turned pastry prodigy. Wears an apron like a tailored suit and apologises to ovens when they overheat.",
      color: "#fde047",
      emoji: "🧁",
      rel: ["trust", "affection"],
    },
    {
      id: "dot",
      name: "Dot Beaumont",
      role: "Dame Dorothy, head judge",
      blurb: "Has tasted more soggy bottoms than any woman alive. Terrifying. Secretly sentimental.",
      color: "#f9a8d4",
      emoji: "🫖",
      rel: ["respect"],
    },
    {
      id: "bryce",
      name: "Bryce Halloran",
      role: "Executive producer",
      blurb: "Loves ratings more than people. Thinks \"drama\" is a flavour.",
      color: "#fb923c",
      emoji: "🎬",
      rel: [],
    },
  ],
  flags: {
    shared_secret: { label: "Traded your grandmother's sugar trick", secret: true },
    lemon_tart: { label: "Baked Gran's lemon tart" },
    peeked: { label: "Peeked at Jun's station" },
    flambe_hero: { label: "Turned a fire into a feature" },
    crowd_favourite: { label: "Became the audience favourite", secret: true },
    knows_jun_recipe: { label: "Learned about Jun's grandmother's recipe", secret: true },
    accused_jun: { label: "Accused Jun of sabotage" },
    found_clue: { label: "Found a clue about the saboteur", secret: true },
    told_dot: { label: "Told Dot about the sabotage" },
    dot_moved: { label: "Showed Dot your grandmother's notebook", secret: true },
    exposed_bryce: { label: "Exposed Bryce live on air" },
    blackmailed_bryce: { label: "Blackmailed Bryce" },
    quiet_word: { label: "Quietly told Dot about Bryce" },
  },
  nodes: [
    {
      key: "S6_N01",
      ch: 1,
      title: "The Last Vanilla Pod",
      start: true,
      text: [
        "The Great Crumb & Whisk tent smells of butter, sugar and quiet panic. A cameraman is already filming you blink.",
        "You have one job this morning: reach the pantry, collect one Madagascar vanilla pod, and not cry on television.",
        "There is one pod left. There is also a man in a spotless navy apron, with excellent forearms, whose hand is already on it.",
        "JUN: Sorry, is this yours?",
        "YOU: It's the last one.",
        "JUN: I noticed. I've been noticing all morning. I've been planning this pod since six a.m.",
      ],
      choices: [
        {
          k: "a",
          t: "Offer to split it, like a civilised human.",
          to: "S6_N02",
          fx: { d: { "jun.trust": 1, "jun.affection": 1 } },
        },
        {
          k: "b",
          t: "Snatch it and run.",
          to: "S6_N02",
          fx: { d: { poise: -1, "jun.trust": -1 } },
          echo: "You hear him say \"Wow\" behind you, with real respect.",
        },
        {
          k: "c",
          t: "Trade him your gran's secret sugar trick for the pod.",
          to: "S6_N02",
          gems: 10,
          fx: { d: { "jun.trust": 2, creativity: 1 }, f: ["shared_secret"] },
        },
      ],
    },
    {
      key: "S6_N02",
      ch: 2,
      title: "The Signature Bake",
      text: [
        "Dame Dorothy Beaumont sweeps into the tent in a mustard cardigan, carrying a clipboard like a war crime.",
        "DOT: Welcome, bakers. Your signature bake is 'A Taste Of Home'. You have two hours. If I find a single soggy bottom, I will say so, and I will say it slowly.",
        "Your hands are shaking. The notebook in your pocket is the only thing keeping you upright: your grandmother's handwriting, buttery and stained, with a recipe for lemon tart on page nine.",
        "Across the tent, Jun is whisking something complicated with a look of deep spiritual joy.",
      ],
      choices: [
        {
          k: "a",
          t: "Bake your grandmother's lemon tart. Exactly as she made it.",
          to: "S6_N03",
          fx: { d: { creativity: 1, "dot.respect": 1 }, f: ["lemon_tart"] },
        },
        {
          k: "b",
          t: "Go wild: a molecular lemon cloud in a spun-sugar cage.",
          to: "S6_N03",
          fx: { d: { creativity: 2, poise: -1 } },
        },
        {
          k: "c",
          t: "Bake something safe, elegant and unarguable.",
          to: "S6_N03",
          fx: { d: { poise: 2 } },
        },
      ],
    },
    {
      key: "S6_N03",
      ch: 3,
      title: "The Technical Challenge",
      text: [
        "The technical challenge is a mystery bake. A single sheet of paper, a pile of ingredients, and the cheerful words: \"Kouign-amann. Good luck.\"",
        "You have never heard of a kouign-amann. It sounds like a Breton sneeze.",
        when({ flags: ["lemon_tart"] }, "Dot gives you a long, unreadable look. \"Lemon,\" she mutters to herself, and writes something down."),
        "Two stations over, Jun is frowning at his own bench, lips moving silently.",
      ],
      choices: [
        {
          k: "a",
          t: "Sneak a peek at Jun's recipe notes.",
          to: "S6_N04",
          fx: { d: { "jun.trust": -1 }, f: ["peeked"] },
          echo: "He sees you. He says nothing. His ears go a very particular shade of pink.",
        },
        {
          k: "b",
          t: "Whisper across the gap and ask for his help.",
          to: "S6_N04",
          fx: { d: { "jun.trust": 1, "jun.affection": 1 } },
        },
        {
          k: "c",
          t: "Trust your instincts and improvise.",
          to: "S6_N04",
          fx: { d: { creativity: 1 } },
        },
      ],
    },
    {
      key: "S6_N04",
      ch: 4,
      title: "The Fire",
      text: [
        "Something under your oven goes whump.",
        "A tongue of yellow flame licks out of the door and up the front of your station. The cameras swing around with the joy of starving animals being fed.",
        "DOT: That is not a soufflé, dear. That is arson.",
        "Four cameras. Two hundred audience members. One fire.",
      ],
      choices: [
        {
          k: "a",
          t: "Smother it with icing sugar and pretend it was planned.",
          to: "S6_N05",
          fx: { d: { creativity: 2 }, f: ["flambe_hero"] },
        },
        {
          k: "b",
          t: "Freeze. Jun arrives with a fire blanket like a knight in a slightly floury apron.",
          to: "S6_N05",
          fx: { d: { "jun.affection": 1, "jun.trust": 1 } },
          echo: "\"You're welcome,\" he says, and then goes bright red as the audience whoops.",
        },
        {
          k: "c",
          t: "Turn it into a show: \"Crème brûlée à la Catastrophe!\"",
          to: "S6_N05",
          gems: 15,
          fx: { d: { creativity: 2, poise: 2, "dot.respect": 2 }, f: ["crowd_favourite"] },
        },
      ],
    },
    {
      key: "S6_N05",
      ch: 5,
      title: "Midnight in the Tent",
      text: [
        "You can't sleep. At midnight you creep back into the silent tent, because nothing soothes an anxious baker like industrial equipment.",
        "There's a single light on at Jun's bench. He's flattening dough with the tender concentration of a man defusing a bomb.",
        when({ flags: ["lemon_tart"] }, "He looks up. \"I tasted your tart, earlier. It was the kind of thing that makes you call your gran.\""),
        "JUN: Couldn't sleep either?",
      ],
      choices: [
        {
          k: "a",
          t: "Pull up a stool and practise together.",
          to: "S6_N06",
          fx: { d: { "jun.affection": 2, "jun.trust": 1 } },
          echo: "Two hours vanish in flour and laughter. Neither of you mention the time.",
        },
        {
          k: "b",
          t: "Ask him about the lemon recipe he keeps scribbling in the margins.",
          to: "S6_N06",
          fx: { d: { "jun.trust": 1 }, f: ["knows_jun_recipe"] },
        },
        {
          k: "c",
          t: "Leave him to it. Rivals don't have midnight chats.",
          to: "S6_N06",
          fx: { d: { poise: 1 } },
        },
      ],
    },
    {
      key: "S6_N06",
      ch: 6,
      title: "The Sabotage",
      text: [
        "When you return to your bench in the morning, your beautiful, carefully measured caster sugar has been replaced by something else. You taste a pinch.",
        "Salt.",
        "You look up. Every baker in the tent is very busy not looking at you. At the far end, Jun is holding a whisk and looking confused.",
        "The cameras are rolling. They are, as always, rolling.",
      ],
      choices: [
        {
          k: "a",
          t: "Accuse Jun in front of everyone.",
          to: "S6_N07",
          major: true,
          fx: { d: { "jun.trust": -3 }, f: ["accused_jun"] },
          echo: "Jun goes very still. \"I see,\" he says, in a voice that's very far from flirty.",
        },
        {
          k: "b",
          t: "Investigate quietly. Look at the cameras, the logs, the footprints.",
          to: "S6_N07",
          major: true,
          fx: { d: { creativity: 1 }, f: ["found_clue"] },
        },
        {
          k: "c",
          t: "Take it to Dot.",
          to: "S6_N07",
          major: true,
          fx: { d: { "dot.respect": 1 }, f: ["told_dot"] },
        },
      ],
    },
    {
      key: "S6_N07",
      ch: 7,
      title: "Dot's Office",
      text: [
        "Dame Dorothy's trailer smells of Earl Grey and discipline. She pours you a cup without asking.",
        "DOT: Somebody in my tent is cheating. I have judged baking for forty years, and I know a sabotaged bake when I taste one.",
        when({ flags: ["accused_jun"] }, "DOT: And I saw your little performance this morning. Was it quite fair?"),
        "She looks at you over her glasses for a long moment.",
        "DOT: Tell me something true about why you're here.",
      ],
      choices: [
        {
          k: "a",
          t: "Confess honestly: you're terrified, and you're baking for someone who's gone.",
          to: "S6_N08",
          fx: { d: { "dot.respect": 2 } },
        },
        {
          k: "b",
          t: "Blame the rival. It was definitely Jun.",
          to: "S6_N08",
          fx: { d: { "dot.respect": -1 } },
        },
        {
          k: "c",
          t: "Slide your grandmother's notebook across the desk.",
          to: "S6_N08",
          gems: 15,
          fx: { d: { "dot.respect": 3, creativity: 1 }, f: ["dot_moved"] },
        },
      ],
    },
    {
      key: "S6_N08",
      ch: 8,
      title: "The Partner Challenge",
      text: [
        "The semi-final is a pairs challenge, and the universe, which clearly has a sense of humour, puts you with Jun.",
        when({ flags: ["accused_jun"] }, "He's scrupulously polite. He hasn't made a single joke all morning, and you miss them more than you expected to."),
        "DOT: You have ninety minutes to produce a joint dessert that represents both of you. I want harmony. I want flavour. I want no fire.",
        "Jun gives you a nervous half-smile over a mountain of egg whites.",
      ],
      choices: [
        {
          k: "a",
          t: "Follow Jun's plan. He clearly knows what he's doing.",
          to: "S6_N09",
          fx: { d: { "jun.trust": 1 } },
        },
        {
          k: "b",
          t: "Take charge. Somebody has to.",
          to: "S6_N09",
          fx: { d: { poise: 1, creativity: 1 } },
        },
        {
          k: "c",
          t: "Suggest a compromise: your lemon, his technique.",
          to: "S6_N09",
          req: { gte: { "jun.trust": 2 } },
          lock: "Jun would need to trust you enough to try it.",
          fx: { d: { creativity: 2, "jun.affection": 1 } },
        },
      ],
    },
    {
      key: "S6_N09",
      ch: 9,
      title: "The Rumour",
      text: [
        "The next morning every newsagent in the county carries the same headline:",
        "## BAKE-OFF RIVALS CAUGHT SNOGGING IN PANTRY!",
        "There is a photograph. It is extremely blurry. It is, in fact, a picture of the two of you both reaching for the same jar of sprinkles.",
        "Bryce Halloran, the executive producer, is hovering near the catering table, looking like a cat that has swallowed a rating.",
      ],
      choices: [
        {
          k: "a",
          t: "Deny it loudly, repeatedly and into every microphone.",
          to: "S6_N10",
          fx: { d: { poise: -1, "jun.affection": -1 } },
        },
        {
          k: "b",
          t: "Own it with humour. \"He was stealing my sprinkles.\"",
          to: "S6_N10",
          fx: { d: { poise: 2, "jun.affection": 1 } },
        },
        {
          k: "c",
          t: "Ask Jun quietly what he wants to do about it.",
          to: "S6_N10",
          fx: { d: { "jun.trust": 1, "jun.affection": 1 } },
          echo: "He blinks at you as though nobody has asked him that before.",
        },
      ],
    },
    {
      key: "S6_N10",
      ch: 10,
      title: "The Real Saboteur",
      text: [
        "It doesn't take a detective. It takes a headline, a blurry photograph and a very pleased man.",
        when({ flags: ["found_clue"] }, "The clue you found, a half-empty sugar bag, is marked with the production company's logo. It fits."),
        "Bryce did it all. The salt. The fire. The leak. A baking show without drama is just a room of people being kind, and he had ratings to protect.",
        "BRYCE: Don't look at me like that. Nobody watches a show about people being nice.",
        "He has no idea how wrong he is.",
      ],
      choices: [
        {
          k: "a",
          t: "Expose him on live television, mid-bake.",
          to: "S6_N11",
          major: true,
          fx: { d: { poise: -1 }, f: ["exposed_bryce"] },
        },
        {
          k: "b",
          t: "Quietly tell Dot what you've learned.",
          to: "S6_N11",
          major: true,
          fx: { d: { "dot.respect": 1 }, f: ["quiet_word"] },
        },
        {
          k: "c",
          t: "Blackmail him with the evidence you've been collecting.",
          to: "S6_N11",
          major: true,
          req: { flags: ["found_clue"] },
          lock: "You'd need some actual evidence first.",
          fx: { d: { creativity: 1 }, f: ["blackmailed_bryce"] },
        },
      ],
    },
    {
      key: "S6_N11",
      ch: 11,
      title: "The Final Bake",
      text: [
        "It's the final. The tent is full. The cameras are rolling, and for once you're glad they are.",
        "Dame Dorothy taps her clipboard. \"Final challenge. One dish. Whatever you choose to bake, I want it to mean something.\"",
        when({ flags: ["accused_jun"] }, "Jun is at the far end of the tent, baking in silence. He hasn't looked at you in days."),
        when({ flags: ["knows_jun_recipe"] }, "You know exactly what Jun is baking: his grandmother's lemon tart, with the secret ingredient she swore him never to tell."),
        "The timer starts.",
      ],
      choices: [
        {
          k: "a",
          t: "Bake the safe, flawless showstopper and go for the win.",
          to: "S6_END_01",
          major: true,
        },
        {
          k: "b",
          t: "Share your station with Jun and bake one tart together.",
          to: "S6_END_02",
          major: true,
          req: { gte: { "jun.trust": 4, "jun.affection": 4 } },
          lock: "You and Jun would need to trust each other, and like each other, much more.",
        },
        {
          k: "c",
          t: "Hand Jun your vanilla, and let him win.",
          to: "S6_END_03",
          major: true,
          req: { gte: { "jun.affection": 5 } },
          lock: "You'd have to care about Jun far more than a trophy.",
        },
        {
          k: "d",
          t: "Bake for yourself and forget the trophy entirely.",
          to: "S6_END_04",
          major: true,
          req: { gte: { creativity: 4, "dot.respect": 3 } },
          lock: "You'd need more creativity, and Dot's respect, to walk away this boldly.",
        },
        {
          k: "e",
          t: "Bake through the scandal with the whole country watching.",
          to: "S6_END_05",
          major: true,
          req: { flags: ["exposed_bryce"], gte: { poise: 3 } },
          lock: "You'd need to have exposed Bryce publicly, and have nerves of steel.",
        },
      ],
    },
    {
      key: "S6_END_01",
      ch: 12,
      title: "Crowned",
      ending: { n: 1, title: "Crowned", type: "neutral" },
      text: [
        "You win. Dame Dorothy hands you a glass trophy shaped like a whisk. The audience screams.",
        "It is, objectively, a triumph. You also, objectively, never once tasted your own tart.",
        when({ flags: ["blackmailed_bryce"] }, "Bryce is conspicuously absent from the champagne. You have never been told why, and nobody asks."),
        when({ flags: ["exposed_bryce"] }, "Bryce is led off the set by two very polite security guards, to a standing ovation."),
        "Across the tent, Jun gives you the tiniest nod. It says: well done. It also says: I don't know what we were doing, but I'll miss it.",
      ],
    },
    {
      key: "S6_END_02",
      ch: 12,
      title: "Two Spoons",
      ending: { n: 2, title: "Two Spoons", type: "romance" },
      text: [
        "You and Jun bake one tart. Two lemons, two hands, one set of slightly terrible jokes.",
        "When Dot tastes it, she goes silent. Then she sets down her spoon, takes off her glasses, and, very quietly, says: \"Oh.\"",
        "Co-champions. The trophy, it turns out, comes in two halves.",
        when({ flags: ["shared_secret"] }, "You swap your grandmothers' secrets at the victory party. Mostly so neither of you will ever be hungry."),
        "JUN: For the record, I was never really after the vanilla.",
        "YOU: I know.",
      ],
    },
    {
      key: "S6_END_03",
      ch: 12,
      title: "The Better Prize",
      ending: { n: 3, title: "The Better Prize", type: "romance" },
      text: [
        "Jun's vanilla ran out an hour ago. You watch his face fall as he realises, and then you hand him yours.",
        "JUN: You can't. This is the final.",
        "YOU: I can. I'm very much doing it.",
        "He wins. You don't. It's the most disastrous decision of your baking career, and you're smiling so much your cheeks hurt.",
        "Afterwards, in the empty tent, he hands you the trophy and a single lemon tart.",
        "JUN: Half of it is yours. All of it is yours. I'm not very good at this.",
        "You kiss him. The cameras have already been turned off. This one is just for you.",
      ],
    },
    {
      key: "S6_END_04",
      ch: 12,
      title: "The Bakery on Marlowe Street",
      ending: { n: 4, title: "The Bakery on Marlowe Street", type: "hopeful" },
      text: [
        "You bake something that's entirely yours. Nobody's recipe. Nobody's trophy. Just a tart that tastes the way your grandmother's kitchen smelled.",
        "You don't win. Dame Dorothy, however, finds you by the exit with a business card.",
        "DOT: There's a shop going on Marlowe Street. Tiny, awful, the best oven in Britain. I'll back you.",
        "A year later there's a queue round the corner every morning.",
        when({ gte: { "jun.affection": 3 } }, "Jun runs the counter at weekends, stealing your vanilla, and your bakery, and, increasingly, your heart."),
        "You hang your grandmother's notebook on the wall, behind glass. Page nine is always open.",
      ],
    },
    {
      key: "S6_END_05",
      ch: 12,
      title: "Live, Mildly Scandalous and Delicious",
      ending: { n: 5, title: "Live, Mildly Scandalous and Delicious", type: "hopeful" },
      text: [
        "You bake through the scandal. The cameras swing wildly between Bryce being escorted out, Jun looking stunned, and you icing a tart with a perfectly steady hand.",
        "It is the highest-rated episode in the show's history. Nobody watching is entirely sure what happened, except that it was wonderful.",
        "You win by public vote, by a landslide. Dame Dorothy hands you the trophy with a look of deep, weary admiration.",
        "DOT: That was the most unprofessional thing I've ever seen. I loved every second.",
        when({ gte: { "jun.affection": 3 } }, "Jun lifts you off your feet in front of four cameras. It's much more tasteful than the pantry photo. Marginally."),
      ],
    },
  ],
};
