import { when } from "./dsl";
import type { StoryDef } from "./types";

export const stealingTomorrow: StoryDef = {
  slug: "art-of-stealing-tomorrow",
  title: "The Art of Stealing Tomorrow",
  tagline: "One night. One diamond. The one thief you swore you'd never trust.",
  description:
    "You're an assistant curator at London's Bellgrave Museum. A priceless diamond called The Black Sun is on display for one night only, and you've received an anonymous invitation: steal the diamond with me, and I'll tell you why your father was blamed for the museum robbery fifteen years ago. The thief waiting for you after midnight is the one person you promised yourself you'd never trust.",
  genres: ["Romance", "Heist", "Thriller", "Comedy"],
  rating: "16+",
  setting: "The Bellgrave Museum, London, after midnight",
  tone: "Stylish, fast-paced, flirtatious, suspenseful",
  cover: { from: "#be123c", to: "#3b0764", emoji: "💎", image: "/covers/the-art-of-stealing-tomorrow.jpg" },
  stats: [
    { id: "cleverness", label: "Cleverness" },
    { id: "notoriety", label: "Notoriety" },
  ],
  characters: [
    {
      id: "luca",
      name: "Luca Moretti",
      role: "The world's most wanted art thief",
      blurb: "Charming, infuriating and always three moves ahead. He claims he's on your side. He claims many things.",
      color: "#fda4af",
      emoji: "🕶️",
      rel: ["trust", "affection"],
    },
    {
      id: "shaw",
      name: "Detective Evelyn Shaw",
      role: "Metropolitan Police, Art & Antiques",
      blurb: "Sharp, patient and tired of being lied to by people in expensive coats.",
      color: "#93c5fd",
      emoji: "🕵️",
      rel: ["trust"],
    },
    {
      id: "bea",
      name: "Bea Okafor",
      role: "Luca's tech wizard",
      blurb: "Runs the crew's security bypasses from a catering van, and narrates everything with sarcasm and snacks.",
      color: "#86efac",
      emoji: "🎧",
      rel: [],
    },
    {
      id: "crane",
      name: "Sebastian Crane",
      role: "Museum Director",
      blurb: "Smiles at donors, pockets their donations, and has been laundering stolen art for fifteen years.",
      color: "#fcd34d",
      emoji: "🎭",
      rel: [],
    },
  ],
  flags: {
    trusted_luca: { label: "Trusted Luca" },
    trusted_shaw: { label: "Trusted Detective Shaw" },
    double_agent: { label: "Played both sides in secret", secret: true },
    forged_pass: { label: "Used a forged pass", secret: true },
    befriended_bea: { label: "Won Bea over" },
    studied_blueprints: { label: "Memorised the floor plans", secret: true },
    used_bea: { label: "Got Bea's help in the laser room", secret: true },
    double_cross: { label: "Pretended to accept the Director's deal" },
    betrayed_luca: { label: "Betrayed Luca" },
    both_keys: { label: "Opened the vault with both keys", secret: true },
    forced_vault: { label: "Broke into the vault alone", secret: true },
    expose_truth: { label: "Exposed the truth" },
    stole_black_diamond: { label: "Stole the Black Sun" },
    police_evidence: { label: "Gave the evidence to Shaw" },
    rooftop_escape: { label: "Escaped across the rooftops with Luca", secret: true },
  },
  nodes: [
    {
      key: "S2_N01",
      ch: 1,
      title: "The Thief",
      start: true,
      text: [
        "You find Luca Moretti sitting inside the museum café, boots on a chair, like a man waiting for a delayed train.",
        "He raises his coffee.",
        "LUCA: You're late.",
        "YOU: You broke into a secure museum.",
        "LUCA: Technically I was invited.",
        "YOU: By whom?",
        "He smiles.",
        "LUCA: Hopefully, you.",
      ],
      choices: [
        { k: "a", t: "Ask about your father.", to: "S2_N02A", fx: { d: { cleverness: 1 } } },
        {
          k: "b",
          t: "Threaten to call security.",
          to: "S2_N02B",
          fx: { d: { notoriety: 1, "luca.trust": -1 } },
          echo: "Luca sips his coffee. He doesn't look worried. He looks impressed.",
        },
        {
          k: "c",
          t: "Pretend to join his heist immediately.",
          to: "S2_N02C",
          gems: 15,
          fx: { d: { "luca.trust": 2, "luca.affection": 1 }, f: ["trusted_luca"] },
        },
      ],
    },
    {
      key: "S2_N02A",
      ch: 1,
      title: "Your Father's Name",
      text: [
        "YOU: My father. Fifteen years ago. Start talking.",
        "Luca's smile goes carefully neutral.",
        "LUCA: Charles Harrow. Senior conservator. Convicted of stealing the Helios collection, and dead before his appeal.",
        "You hadn't heard anyone say his name out loud in years.",
        "LUCA: He didn't do it.",
      ],
      next: "S2_N02",
    },
    {
      key: "S2_N02B",
      ch: 1,
      title: "An Unimpressed Thief",
      text: [
        "YOU: I'm calling security.",
        "LUCA: They're playing cards in the basement. I sent them a very convincing pizza.",
        "He slides a folded note across the table. In your father's handwriting: a single line, a single date, the night of the robbery.",
        "LUCA: Sit down. Then shout at me if you still want to.",
      ],
      next: "S2_N02",
    },
    {
      key: "S2_N02C",
      ch: 1,
      title: "Partners, Apparently",
      text: [
        "YOU: Fine. I'm in. What's the plan?",
        "Luca stares at you over the rim of his cup. For once he doesn't have a witty reply.",
        "LUCA: That was either very brave or very stupid.",
        "YOU: Both. Usually both.",
        "He laughs, properly, and it changes his whole face. You realise you'd like to hear it again, which is a problem.",
      ],
      next: "S2_N02",
    },
    {
      key: "S2_N02",
      ch: 2,
      title: "The Offer",
      text: [
        "Luca explains. Your father was framed. The real thief was connected to the museum's current director, Sebastian Crane.",
        "The Black Sun, tonight's star exhibit, contains an embedded tracking mechanism proving where it was originally smuggled from: the same pipeline that took the Helios collection.",
        "YOU: And you want to steal it.",
        "LUCA: I want to borrow it. Briefly. Dramatically.",
        "You agree to help, but on one condition: you get answers. All of them.",
      ],
      next: "S2_N02X",
    },
    {
      key: "S2_N02X",
      ch: 2,
      title: "The Crew",
      text: [
        "The crew works from a catering van parked behind the loading dock. Inside, a woman in a hoodie is eating crisps and typing at frightening speed.",
        "BEA: This is the curator? She's shorter than her security photo.",
        "LUCA: Bea Okafor. She'll be in your ear all night. She's rude, but she's never been wrong.",
        "BEA: I've been wrong twice. Both times it was somebody else's fault.",
        "Floor plans are spread across every surface in the van.",
      ],
      choices: [
        {
          k: "a",
          t: "Compliment Bea's setup — sincerely.",
          to: "S2_N03",
          fx: { f: ["befriended_bea"] },
          echo: "Bea pauses mid-crisp. \"Okay. She can stay.\"",
        },
        {
          k: "b",
          t: "Ask Luca, privately, what he isn't telling you.",
          to: "S2_N03",
          fx: { d: { "luca.trust": 1, "luca.affection": 1 } },
        },
        {
          k: "c",
          t: "Study the floor plans until you know every door.",
          to: "S2_N03",
          fx: { d: { cleverness: 1 }, f: ["studied_blueprints"] },
        },
      ],
    },
    {
      key: "S2_N03",
      ch: 3,
      title: "The First Checkpoint",
      text: [
        "You reach the restricted gallery. Halfway down the corridor, a security officer steps out of the shadows with a torch.",
        "OFFICER: Nobody's on the rota tonight.",
        when({ flags: ["studied_blueprints"] }, "You know exactly which camera covers this corridor and exactly how long its blind spot lasts. About four seconds."),
        when({ flags: ["trusted_luca"] }, "Luca's hand rests lightly on the small of your back. He's very good at seeming like he belongs."),
      ],
      choices: [
        { k: "a", t: "Talk your way through.", to: "S2_N04A", fx: { d: { cleverness: 1 } } },
        { k: "b", t: "Distract the guard.", to: "S2_N04B", fx: { d: { notoriety: 1 } } },
        {
          k: "c",
          t: "Use Luca's forged identity.",
          to: "S2_N04C",
          gems: 10,
          fx: { d: { cleverness: 2, "luca.trust": 1 }, f: ["forged_pass"] },
        },
      ],
    },
    {
      key: "S2_N04A",
      ch: 3,
      title: "A Confident Lie",
      text: [
        "YOU: Conservation audit. Ask the Director's office why you weren't told.",
        "You flash your staff badge with exactly the right mixture of boredom and contempt.",
        "The guard hesitates, then steps aside.",
        "LUCA: (low) That was offensively good.",
      ],
      next: "S2_N04",
    },
    {
      key: "S2_N04B",
      ch: 3,
      title: "A Small Fire Alarm",
      text: [
        "You pull a fire alarm three galleries away. It is the least subtle option available and it works beautifully.",
        "The guard sprints off. You and Luca slip inside.",
        "LUCA: Remind me never to annoy you.",
        "You are fairly sure that was a compliment.",
      ],
      next: "S2_N04",
    },
    {
      key: "S2_N04C",
      ch: 3,
      title: "Dr. Edmund Fairweather",
      text: [
        "Luca hands you a lanyard. The photograph is of a stranger; the name is Dr. Edmund Fairweather, Visiting Fellow, Antwerp.",
        "The guard inspects it for so long that you start planning a retirement in another country.",
        "OFFICER: Nice to have a proper scholar around, for once.",
        "LUCA: (low) I gave him a Belgian accent. You're welcome.",
      ],
      next: "S2_N04",
    },
    {
      key: "S2_N04",
      ch: 4,
      title: "The Laser Room",
      text: [
        "The diamond is suspended inside a glass case. Red security lasers cross the room in a pattern that looks, unhelpfully, like a spider's web.",
        "LUCA: Stay close.",
        "YOU: That sounds suspicious.",
        "LUCA: Most useful things do.",
        when({ flags: ["befriended_bea"] }, "In your ear, Bea crackles to life: \"Whenever you're ready, Curator. I'm enjoying this way too much.\""),
      ],
      choices: [
        {
          k: "a",
          t: "Disable the system manually.",
          to: "S2_N05",
          req: { gte: { cleverness: 2 } },
          lock: "You'd need sharper instincts to touch that panel.",
          fx: { d: { cleverness: 2 } },
        },
        {
          k: "b",
          t: "Let Luca handle it.",
          to: "S2_N05",
          fx: { d: { "luca.trust": 1, "luca.affection": 1 } },
        },
        {
          k: "c",
          t: "Bluff the security technician on the intercom.",
          to: "S2_N05",
          fx: { d: { notoriety: 1 } },
        },
        {
          k: "d",
          t: "Whisper into your earpiece: \"Bea, talk me through it.\"",
          to: "S2_N05",
          req: { flags: ["befriended_bea"] },
          hide: true,
          fx: { d: { cleverness: 1 }, f: ["used_bea"] },
          echo: "Bea's voice is steady and warm in your ear, like a hand on your shoulder.",
        },
      ],
    },
    {
      key: "S2_N05",
      ch: 5,
      title: "The Black Sun",
      text: [
        "You reach the display. The diamond is smaller than you expected. Almost ordinary.",
        "Luca studies it for a long moment.",
        "LUCA: That's not the real diamond.",
        "You stare at him.",
        "YOU: What?",
        "The lights come on, every one of them at once. A woman in a grey coat steps out from behind a pillar with a badge in one hand and a very steady gun in the other.",
        "SHAW: Nobody move.",
        "The entire heist was a trap.",
      ],
      next: "S2_N06",
    },
    {
      key: "S2_N06",
      ch: 5,
      title: "The Detective",
      text: [
        "Detective Evelyn Shaw has been investigating the Bellgrave for months. She lowers the gun by about an inch.",
        "SHAW: Sit. Both of you. I'm not here to arrest Luca, I'm here because he's the only honest thief in London.",
        "LUCA: I'm flattered. And insulted.",
        "SHAW: Sebastian Crane is moving the real diamond tonight. I need someone on the inside who knows this museum. That's you.",
        "You now have two alliances on the table.",
      ],
      choices: [
        {
          k: "a",
          t: "Trust Luca.",
          to: "S2_N07",
          major: true,
          fx: { d: { "luca.trust": 2, "luca.affection": 1 }, f: ["trusted_luca"] },
        },
        {
          k: "b",
          t: "Work with Shaw.",
          to: "S2_N07",
          major: true,
          fx: { d: { "shaw.trust": 2 }, f: ["trusted_shaw"] },
        },
        {
          k: "c",
          t: "Secretly work with both.",
          to: "S2_N07",
          gems: 20,
          major: true,
          fx: {
            d: { cleverness: 2, "luca.trust": 1, "shaw.trust": 1 },
            f: ["double_agent", "trusted_luca", "trusted_shaw"],
          },
        },
      ],
    },
    {
      key: "S2_N07",
      ch: 6,
      title: "The Double Cross",
      text: [
        "The service lift opens. Sebastian Crane steps out in a dinner jacket, applauding softly.",
        "CRANE: Bravo. Truly. I wondered which of you would come.",
        "He swapped the diamond hours ago. The real Black Sun is in the private vault beneath the museum. He doesn't seem worried about telling you so; he seems to be enjoying it.",
        "CRANE: Give me Luca. Quietly, tonight. Your father's name will be cleared by morning.",
        "It is, horribly, a reasonable offer.",
      ],
      choices: [
        {
          k: "a",
          t: "Reject the deal.",
          to: "S2_N08A",
          major: true,
          fx: { d: { "luca.trust": 2 } },
        },
        {
          k: "b",
          t: "Pretend to accept.",
          to: "S2_N08B",
          major: true,
          fx: { d: { cleverness: 2 }, f: ["double_cross"] },
        },
        {
          k: "c",
          t: "Accept his deal.",
          to: "S2_N08C",
          major: true,
          fx: { d: { "luca.trust": -5 }, f: ["betrayed_luca"] },
          echo: "Luca doesn't say anything. That's the worst part.",
        },
      ],
    },
    {
      key: "S2_N08A",
      ch: 6,
      title: "No Deal",
      text: [
        "YOU: My father wasn't a thief. And neither is he.",
        "Crane's smile doesn't move. It is a painted smile.",
        "CRANE: Then you'll all learn what the Bellgrave does to people who can't be bought.",
        "Luca's hand brushes yours, barely. It says thank you in a language you're not ready to translate.",
      ],
      next: "S2_N08",
    },
    {
      key: "S2_N08B",
      ch: 6,
      title: "A Very Convincing Liar",
      text: [
        "YOU: Fine. Tell me where and when.",
        "Crane beams and pours you a glass of something expensive. Across the lobby, Luca goes completely still.",
        "You keep your eyes on the Director. You do not look at Luca. You do not look at Shaw. You tell the lie of your life.",
        "Only later, when Crane turns away, do you risk a wink at Luca. He exhales, and the colour comes back into his face.",
      ],
      next: "S2_N08",
    },
    {
      key: "S2_N08C",
      ch: 6,
      title: "The Price of a Name",
      text: [
        "YOU: Deal.",
        "It is very quiet. Luca's face does something you will remember for years: nothing at all.",
        "LUCA: I see.",
        "Security drags him toward the lift. He doesn't fight. He only looks back at you once, with the kind of patience that has given up.",
        "Shaw glares at you with open disgust. You have your father's name now. You have never felt so empty.",
      ],
      next: "S2_N08",
    },
    {
      key: "S2_N08",
      ch: 7,
      title: "The Private Vault",
      text: [
        "The real diamond is kept beneath the museum, behind a vault door that requires two keys. One key is held by Luca. The other is held by Shaw.",
        "Who helps you now depends entirely on how you've treated them tonight.",
        when({ flags: ["betrayed_luca"] }, "Luca is in a cell upstairs. You wonder whether he would have handed you the key, if you'd let him."),
        when({ flags: ["trusted_luca"], notFlags: ["betrayed_luca"] }, "Luca presses his key into your palm. \"I've been waiting for you to choose me.\""),
        when({ flags: ["trusted_shaw"] }, "Shaw's voice is dry. \"Don't make me regret this.\""),
      ],
      choices: [
        {
          k: "a",
          t: "Take Luca's key.",
          to: "S2_N09",
          req: { flags: ["trusted_luca"], notFlags: ["betrayed_luca"] },
          lock: "Luca isn't handing you anything.",
          fx: { d: { "luca.affection": 1 } },
        },
        {
          k: "b",
          t: "Accept Shaw's key.",
          to: "S2_N09",
          req: { flags: ["trusted_shaw"] },
          lock: "Shaw doesn't trust you with it.",
          fx: { d: { "shaw.trust": 1 } },
        },
        {
          k: "c",
          t: "Use both keys, and let both of them stand beside you.",
          to: "S2_N09",
          req: { flags: ["double_agent"] },
          hide: true,
          fx: { d: { "luca.trust": 1, "shaw.trust": 1 }, f: ["both_keys"] },
        },
        {
          k: "d",
          t: "Break in alone.",
          to: "S2_N09",
          fx: { d: { cleverness: 1, notoriety: 1 }, f: ["forced_vault"] },
        },
      ],
    },
    {
      key: "S2_N09",
      ch: 8,
      title: "The Truth",
      text: [
        "Inside the vault you find the original evidence from fifteen years ago. Your father was not stealing.",
        "He had discovered that the museum's director was laundering stolen artwork, and was framed to keep the operation secret.",
        when(
          { notFlags: ["betrayed_luca"] },
          "Luca stands in the door. He has spent years collecting the other half of this evidence.",
          "LUCA: I didn't bring you here for the diamond.",
          "YOU: Then why?",
          "LUCA: Because you're the only person who can decide what happens next.",
        ),
        when(
          { flags: ["betrayed_luca"] },
          "A note is tucked into the evidence folder in a familiar hand: \"He knew I'd try. I left this for you anyway. — L\"",
          "Your chest aches. Luca was never going to take the diamond.",
        ),
      ],
      choices: [
        {
          k: "a",
          t: "Expose everything publicly.",
          to: "S2_N10",
          major: true,
          fx: { f: ["expose_truth"] },
        },
        {
          k: "b",
          t: "Destroy the evidence and leave with the diamond.",
          to: "S2_N10",
          major: true,
          fx: { d: { notoriety: 3 }, f: ["stole_black_diamond"] },
        },
        {
          k: "c",
          t: "Give the evidence to Shaw.",
          to: "S2_N10",
          major: true,
          fx: { d: { "shaw.trust": 2 }, f: ["police_evidence"] },
        },
      ],
    },
    {
      key: "S2_N10",
      ch: 9,
      title: "The Escape",
      text: [
        "Police surround the museum. Blue light pulses through the skylights.",
        when({ notFlags: ["betrayed_luca"] }, "Luca reaches for your hand. \"There's a roof exit.\""),
        when({ flags: ["betrayed_luca"] }, "Luca stands by the roof exit. He doesn't look at you. \"Come or don't. I'm leaving either way.\""),
        "Below, a sergeant is shouting for someone to hold the lift.",
      ],
      choices: [
        {
          k: "a",
          t: "Follow Luca onto the roof.",
          to: "S2_N11",
          gems: 15,
          fx: { d: { "luca.affection": 2, "luca.trust": 1 }, f: ["rooftop_escape"] },
        },
        {
          k: "b",
          t: "Take Luca's hand and run for the underground tunnel.",
          to: "S2_N11",
          req: { notFlags: ["betrayed_luca"] },
          hide: true,
          fx: { d: { "luca.affection": 1, cleverness: 1 } },
        },
        {
          k: "c",
          t: "Slip away through the tunnel alone.",
          to: "S2_N11",
          fx: { d: { cleverness: 1 } },
        },
        {
          k: "d",
          t: "Surrender.",
          to: "S2_N11",
          fx: { d: { "shaw.trust": 1 } },
        },
      ],
    },
    {
      key: "S2_N11",
      ch: 10,
      title: "The Final Choice",
      text: [
        "The helicopter lights appear above the museum, turning the skylight white.",
        "Your father's name can finally be cleared. But stealing the diamond makes you a criminal.",
        when({ flags: ["stole_black_diamond"] }, "The diamond is warm in your hand, like something alive."),
        "Whatever you do next, you'll be doing it for the rest of your life.",
      ],
      choices: [
        {
          k: "a",
          t: "Return the diamond and expose the truth.",
          to: "S2_END_01",
          major: true,
        },
        {
          k: "b",
          t: "Keep the diamond and disappear with Luca.",
          to: "S2_END_02",
          major: true,
          req: { gte: { "luca.affection": 5, "luca.trust": 5 } },
          lock: "You and Luca aren't close enough to vanish together.",
        },
        {
          k: "c",
          t: "Give everything to Shaw.",
          to: "S2_END_03",
          major: true,
          req: { gte: { "shaw.trust": 4 } },
          lock: "Shaw doesn't trust you enough to take that risk.",
        },
        {
          k: "d",
          t: "Keep the diamond and become a professional thief.",
          to: "S2_END_04",
          major: true,
          req: { gte: { notoriety: 4 } },
          lock: "You're not notorious enough to vanish into the underworld.",
        },
        {
          k: "e",
          t: "Run the long con: let the Director take the fall himself.",
          to: "S2_END_05",
          major: true,
          req: { flags: ["double_cross"], gte: { cleverness: 4 } },
          lock: "You'd need to have played along with the Director, and be far cleverer than you've been.",
        },
      ],
    },
    {
      key: "S2_END_01",
      ch: 11,
      title: "The Truth",
      ending: { n: 1, title: "The Truth", type: "hopeful" },
      text: [
        "The evidence reaches the public. Your father's name is cleared. The museum director is arrested on live television.",
        "Luca watches from across the courtroom, in a tailored suit that cost more than your rent.",
        when(
          { gte: { "luca.affection": 4 }, notFlags: ["betrayed_luca"] },
          "When you step outside into the rain, he is waiting on the pavement with an umbrella and two coffees.",
          "LUCA: Technically, I was invited.",
        ),
        when(
          { flags: ["betrayed_luca"] },
          "You look for Luca afterwards. He's already gone. You find an empty coffee cup with your name scrawled on it, and nothing more.",
        ),
        when(
          { lte: { "luca.affection": 3 }, notFlags: ["betrayed_luca"] },
          "Before you can speak, he's gone, leaving a single chocolate on the bench. It's your favourite brand. You never told him.",
        ),
      ],
    },
    {
      key: "S2_END_02",
      ch: 11,
      title: "Partners in Crime",
      ending: { n: 2, title: "Partners in Crime", type: "romance" },
      text: [
        "You and Luca vanish over the rooftops as the helicopter sweeps the skylight.",
        "Months later, an art gallery in Paris receives an anonymous donation. The Black Sun is returned, in perfect condition, with a note:",
        "> We borrowed it.",
        when({ flags: ["rooftop_escape"] }, "The note is signed with a tiny drawing of a rooftop and two figures, hand in hand."),
        "Your new life with Luca begins, somewhere with good coffee and terrible security.",
      ],
    },
    {
      key: "S2_END_03",
      ch: 11,
      title: "The Clean Exit",
      ending: { n: 3, title: "The Clean Exit", type: "hopeful" },
      text: [
        "Shaw exposes the museum's criminal operation. You walk away with your reputation intact and your father's name restored.",
        "On the steps of the Bellgrave you find Luca, leaning on a pillar as if he owned it.",
        "LUCA: You're much more dangerous than I expected.",
        "He gives you one last smile, and disappears into the London crowd.",
        when({ flags: ["double_agent"] }, "Shaw catches your eye across the steps. She knows what you did. She lets it go."),
      ],
    },
    {
      key: "S2_END_04",
      ch: 11,
      title: "The Black Sun",
      ending: { n: 4, title: "The Black Sun", type: "dark" },
      text: [
        "You disappear with the diamond. Years later, your name is whispered among art thieves across Europe. Nobody knows who you really are.",
        "Except Luca. And he is the only person who knows where to find you.",
        when({ gte: { "luca.affection": 7 } }, "You don't work alone for long. Luca is always somewhere on the next rooftop, pretending it's a coincidence."),
        when({ flags: ["betrayed_luca"] }, "And Luca hasn't forgotten the Director's offer. In the sequel, he's your enemy, and he has never once stopped looking."),
      ],
    },
    {
      key: "S2_END_05",
      ch: 11,
      title: "The Long Con",
      ending: { n: 5, title: "The Long Con", type: "neutral" },
      text: [
        "The Director thinks he owns you. That is his mistake.",
        "By dawn, Crane's own account ledgers are in Shaw's hands, the real Black Sun is back in its case, and every camera in the building shows him signing for the forged replacement.",
        "It's the cleanest sting in the Met's history. Nobody is sure who ran it.",
        when({ flags: ["used_bea"] }, "A single message lands in your inbox from an unknown number: \"Best night of my career. Next time bring snacks. — B\""),
        "Luca raises a glass across the room. He has never looked prouder of anyone.",
      ],
    },
  ],
};
